*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: YZ_V_DQDC_CONF..................................*
FORM GET_DATA_YZ_V_DQDC_CONF.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM YZTABL_DQDC_CONF WHERE
(VIM_WHERETAB) .
    CLEAR YZ_V_DQDC_CONF .
YZ_V_DQDC_CONF-MANDT =
YZTABL_DQDC_CONF-MANDT .
YZ_V_DQDC_CONF-USMD_SEARCH_MODE =
YZTABL_DQDC_CONF-USMD_SEARCH_MODE .
YZ_V_DQDC_CONF-USMD_MODEL =
YZTABL_DQDC_CONF-USMD_MODEL .
YZ_V_DQDC_CONF-SCOPE_ID =
YZTABL_DQDC_CONF-SCOPE_ID .
YZ_V_DQDC_CONF-TEMPLATE_ID =
YZTABL_DQDC_CONF-TEMPLATE_ID .
YZ_V_DQDC_CONF-MATCH_PROFILE_ID =
YZTABL_DQDC_CONF-MATCH_PROFILE_ID .
YZ_V_DQDC_CONF-ENTITY =
YZTABL_DQDC_CONF-ENTITY .
YZ_V_DQDC_CONF-ATTR_NAME =
YZTABL_DQDC_CONF-ATTR_NAME .
YZ_V_DQDC_CONF-WEIGTAGE =
YZTABL_DQDC_CONF-WEIGTAGE .
YZ_V_DQDC_CONF-MANDTORY =
YZTABL_DQDC_CONF-MANDTORY .
YZ_V_DQDC_CONF-ATTR_SEQUENCE =
YZTABL_DQDC_CONF-ATTR_SEQUENCE .
YZ_V_DQDC_CONF-FUZZINESS =
YZTABL_DQDC_CONF-FUZZINESS .
YZ_V_DQDC_CONF-EXCLUDE_FROM_SEARCH =
YZTABL_DQDC_CONF-EXCLUDE_FROM_SEARCH .
YZ_V_DQDC_CONF-ACTIVE =
YZTABL_DQDC_CONF-ACTIVE .
<VIM_TOTAL_STRUC> = YZ_V_DQDC_CONF.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_YZ_V_DQDC_CONF .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO YZ_V_DQDC_CONF.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_YZ_V_DQDC_CONF-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM YZTABL_DQDC_CONF WHERE
  USMD_SEARCH_MODE = YZ_V_DQDC_CONF-USMD_SEARCH_MODE AND
  USMD_MODEL = YZ_V_DQDC_CONF-USMD_MODEL AND
  SCOPE_ID = YZ_V_DQDC_CONF-SCOPE_ID AND
  TEMPLATE_ID = YZ_V_DQDC_CONF-TEMPLATE_ID AND
  MATCH_PROFILE_ID = YZ_V_DQDC_CONF-MATCH_PROFILE_ID AND
  ENTITY = YZ_V_DQDC_CONF-ENTITY AND
  ATTR_NAME = YZ_V_DQDC_CONF-ATTR_NAME .
    IF SY-SUBRC = 0.
    DELETE YZTABL_DQDC_CONF .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM YZTABL_DQDC_CONF WHERE
  USMD_SEARCH_MODE = YZ_V_DQDC_CONF-USMD_SEARCH_MODE AND
  USMD_MODEL = YZ_V_DQDC_CONF-USMD_MODEL AND
  SCOPE_ID = YZ_V_DQDC_CONF-SCOPE_ID AND
  TEMPLATE_ID = YZ_V_DQDC_CONF-TEMPLATE_ID AND
  MATCH_PROFILE_ID = YZ_V_DQDC_CONF-MATCH_PROFILE_ID AND
  ENTITY = YZ_V_DQDC_CONF-ENTITY AND
  ATTR_NAME = YZ_V_DQDC_CONF-ATTR_NAME .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR YZTABL_DQDC_CONF.
    ENDIF.
YZTABL_DQDC_CONF-MANDT =
YZ_V_DQDC_CONF-MANDT .
YZTABL_DQDC_CONF-USMD_SEARCH_MODE =
YZ_V_DQDC_CONF-USMD_SEARCH_MODE .
YZTABL_DQDC_CONF-USMD_MODEL =
YZ_V_DQDC_CONF-USMD_MODEL .
YZTABL_DQDC_CONF-SCOPE_ID =
YZ_V_DQDC_CONF-SCOPE_ID .
YZTABL_DQDC_CONF-TEMPLATE_ID =
YZ_V_DQDC_CONF-TEMPLATE_ID .
YZTABL_DQDC_CONF-MATCH_PROFILE_ID =
YZ_V_DQDC_CONF-MATCH_PROFILE_ID .
YZTABL_DQDC_CONF-ENTITY =
YZ_V_DQDC_CONF-ENTITY .
YZTABL_DQDC_CONF-ATTR_NAME =
YZ_V_DQDC_CONF-ATTR_NAME .
YZTABL_DQDC_CONF-WEIGTAGE =
YZ_V_DQDC_CONF-WEIGTAGE .
YZTABL_DQDC_CONF-MANDTORY =
YZ_V_DQDC_CONF-MANDTORY .
YZTABL_DQDC_CONF-ATTR_SEQUENCE =
YZ_V_DQDC_CONF-ATTR_SEQUENCE .
YZTABL_DQDC_CONF-FUZZINESS =
YZ_V_DQDC_CONF-FUZZINESS .
YZTABL_DQDC_CONF-EXCLUDE_FROM_SEARCH =
YZ_V_DQDC_CONF-EXCLUDE_FROM_SEARCH .
YZTABL_DQDC_CONF-ACTIVE =
YZ_V_DQDC_CONF-ACTIVE .
    IF SY-SUBRC = 0.
    UPDATE YZTABL_DQDC_CONF ##WARN_OK.
    ELSE.
    INSERT YZTABL_DQDC_CONF .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_YZ_V_DQDC_CONF-UPD_FLAG,
STATUS_YZ_V_DQDC_CONF-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_YZ_V_DQDC_CONF.
  SELECT SINGLE * FROM YZTABL_DQDC_CONF WHERE
USMD_SEARCH_MODE = YZ_V_DQDC_CONF-USMD_SEARCH_MODE AND
USMD_MODEL = YZ_V_DQDC_CONF-USMD_MODEL AND
SCOPE_ID = YZ_V_DQDC_CONF-SCOPE_ID AND
TEMPLATE_ID = YZ_V_DQDC_CONF-TEMPLATE_ID AND
MATCH_PROFILE_ID = YZ_V_DQDC_CONF-MATCH_PROFILE_ID AND
ENTITY = YZ_V_DQDC_CONF-ENTITY AND
ATTR_NAME = YZ_V_DQDC_CONF-ATTR_NAME .
YZ_V_DQDC_CONF-MANDT =
YZTABL_DQDC_CONF-MANDT .
YZ_V_DQDC_CONF-USMD_SEARCH_MODE =
YZTABL_DQDC_CONF-USMD_SEARCH_MODE .
YZ_V_DQDC_CONF-USMD_MODEL =
YZTABL_DQDC_CONF-USMD_MODEL .
YZ_V_DQDC_CONF-SCOPE_ID =
YZTABL_DQDC_CONF-SCOPE_ID .
YZ_V_DQDC_CONF-TEMPLATE_ID =
YZTABL_DQDC_CONF-TEMPLATE_ID .
YZ_V_DQDC_CONF-MATCH_PROFILE_ID =
YZTABL_DQDC_CONF-MATCH_PROFILE_ID .
YZ_V_DQDC_CONF-ENTITY =
YZTABL_DQDC_CONF-ENTITY .
YZ_V_DQDC_CONF-ATTR_NAME =
YZTABL_DQDC_CONF-ATTR_NAME .
YZ_V_DQDC_CONF-WEIGTAGE =
YZTABL_DQDC_CONF-WEIGTAGE .
YZ_V_DQDC_CONF-MANDTORY =
YZTABL_DQDC_CONF-MANDTORY .
YZ_V_DQDC_CONF-ATTR_SEQUENCE =
YZTABL_DQDC_CONF-ATTR_SEQUENCE .
YZ_V_DQDC_CONF-FUZZINESS =
YZTABL_DQDC_CONF-FUZZINESS .
YZ_V_DQDC_CONF-EXCLUDE_FROM_SEARCH =
YZTABL_DQDC_CONF-EXCLUDE_FROM_SEARCH .
YZ_V_DQDC_CONF-ACTIVE =
YZTABL_DQDC_CONF-ACTIVE .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_YZ_V_DQDC_CONF USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE YZ_V_DQDC_CONF-USMD_SEARCH_MODE TO
YZTABL_DQDC_CONF-USMD_SEARCH_MODE .
MOVE YZ_V_DQDC_CONF-USMD_MODEL TO
YZTABL_DQDC_CONF-USMD_MODEL .
MOVE YZ_V_DQDC_CONF-SCOPE_ID TO
YZTABL_DQDC_CONF-SCOPE_ID .
MOVE YZ_V_DQDC_CONF-TEMPLATE_ID TO
YZTABL_DQDC_CONF-TEMPLATE_ID .
MOVE YZ_V_DQDC_CONF-MATCH_PROFILE_ID TO
YZTABL_DQDC_CONF-MATCH_PROFILE_ID .
MOVE YZ_V_DQDC_CONF-ENTITY TO
YZTABL_DQDC_CONF-ENTITY .
MOVE YZ_V_DQDC_CONF-ATTR_NAME TO
YZTABL_DQDC_CONF-ATTR_NAME .
MOVE YZ_V_DQDC_CONF-MANDT TO
YZTABL_DQDC_CONF-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'YZTABL_DQDC_CONF'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN YZTABL_DQDC_CONF TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'YZTABL_DQDC_CONF'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*

* base table related FORM-routines.............
INCLUDE LSVIMFTX .
