*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: YZ_V_TEMP_DET...................................*
FORM GET_DATA_YZ_V_TEMP_DET.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM YZTAB_TEMPLT_DET WHERE
(VIM_WHERETAB) .
    CLEAR YZ_V_TEMP_DET .
YZ_V_TEMP_DET-CLIENT =
YZTAB_TEMPLT_DET-CLIENT .
YZ_V_TEMP_DET-USMD_MODEL =
YZTAB_TEMPLT_DET-USMD_MODEL .
YZ_V_TEMP_DET-SCOPE_ID =
YZTAB_TEMPLT_DET-SCOPE_ID .
YZ_V_TEMP_DET-TEMPLATE_ID =
YZTAB_TEMPLT_DET-TEMPLATE_ID .
YZ_V_TEMP_DET-VIEW_ID =
YZTAB_TEMPLT_DET-VIEW_ID .
YZ_V_TEMP_DET-COLUMN_ID =
YZTAB_TEMPLT_DET-COLUMN_ID .
YZ_V_TEMP_DET-USMD_ENTITY =
YZTAB_TEMPLT_DET-USMD_ENTITY .
YZ_V_TEMP_DET-USMD_ATTRIBUTE =
YZTAB_TEMPLT_DET-USMD_ATTRIBUTE .
YZ_V_TEMP_DET-ACTIVE_TAB_NAME =
YZTAB_TEMPLT_DET-ACTIVE_TAB_NAME .
YZ_V_TEMP_DET-ACTIVE_FIELD_NAME =
YZTAB_TEMPLT_DET-ACTIVE_FIELD_NAME .
YZ_V_TEMP_DET-FIELD_DOMAIN =
YZTAB_TEMPLT_DET-FIELD_DOMAIN .
YZ_V_TEMP_DET-SEARCHHELP =
YZTAB_TEMPLT_DET-SEARCHHELP .
YZ_V_TEMP_DET-DESCRIPTION =
YZTAB_TEMPLT_DET-DESCRIPTION .
YZ_V_TEMP_DET-FILTER_FIELD_NAME =
YZTAB_TEMPLT_DET-FILTER_FIELD_NAME .
YZ_V_TEMP_DET-AUTO_GENERATE =
YZTAB_TEMPLT_DET-AUTO_GENERATE .
YZ_V_TEMP_DET-SELECTION =
YZTAB_TEMPLT_DET-SELECTION .
YZ_V_TEMP_DET-IS_KEY =
YZTAB_TEMPLT_DET-IS_KEY .
YZ_V_TEMP_DET-INCLUDED =
YZTAB_TEMPLT_DET-INCLUDED .
YZ_V_TEMP_DET-USMD_ACTIVE =
YZTAB_TEMPLT_DET-USMD_ACTIVE .
<VIM_TOTAL_STRUC> = YZ_V_TEMP_DET.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_YZ_V_TEMP_DET .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO YZ_V_TEMP_DET.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_YZ_V_TEMP_DET-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM YZTAB_TEMPLT_DET WHERE
  USMD_MODEL = YZ_V_TEMP_DET-USMD_MODEL AND
  SCOPE_ID = YZ_V_TEMP_DET-SCOPE_ID AND
  TEMPLATE_ID = YZ_V_TEMP_DET-TEMPLATE_ID AND
  VIEW_ID = YZ_V_TEMP_DET-VIEW_ID AND
  COLUMN_ID = YZ_V_TEMP_DET-COLUMN_ID AND
  USMD_ENTITY = YZ_V_TEMP_DET-USMD_ENTITY .
    IF SY-SUBRC = 0.
    DELETE YZTAB_TEMPLT_DET .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM YZTAB_TEMPLT_DET WHERE
  USMD_MODEL = YZ_V_TEMP_DET-USMD_MODEL AND
  SCOPE_ID = YZ_V_TEMP_DET-SCOPE_ID AND
  TEMPLATE_ID = YZ_V_TEMP_DET-TEMPLATE_ID AND
  VIEW_ID = YZ_V_TEMP_DET-VIEW_ID AND
  COLUMN_ID = YZ_V_TEMP_DET-COLUMN_ID AND
  USMD_ENTITY = YZ_V_TEMP_DET-USMD_ENTITY .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR YZTAB_TEMPLT_DET.
    ENDIF.
YZTAB_TEMPLT_DET-CLIENT =
YZ_V_TEMP_DET-CLIENT .
YZTAB_TEMPLT_DET-USMD_MODEL =
YZ_V_TEMP_DET-USMD_MODEL .
YZTAB_TEMPLT_DET-SCOPE_ID =
YZ_V_TEMP_DET-SCOPE_ID .
YZTAB_TEMPLT_DET-TEMPLATE_ID =
YZ_V_TEMP_DET-TEMPLATE_ID .
YZTAB_TEMPLT_DET-VIEW_ID =
YZ_V_TEMP_DET-VIEW_ID .
YZTAB_TEMPLT_DET-COLUMN_ID =
YZ_V_TEMP_DET-COLUMN_ID .
YZTAB_TEMPLT_DET-USMD_ENTITY =
YZ_V_TEMP_DET-USMD_ENTITY .
YZTAB_TEMPLT_DET-USMD_ATTRIBUTE =
YZ_V_TEMP_DET-USMD_ATTRIBUTE .
YZTAB_TEMPLT_DET-ACTIVE_TAB_NAME =
YZ_V_TEMP_DET-ACTIVE_TAB_NAME .
YZTAB_TEMPLT_DET-ACTIVE_FIELD_NAME =
YZ_V_TEMP_DET-ACTIVE_FIELD_NAME .
YZTAB_TEMPLT_DET-FIELD_DOMAIN =
YZ_V_TEMP_DET-FIELD_DOMAIN .
YZTAB_TEMPLT_DET-SEARCHHELP =
YZ_V_TEMP_DET-SEARCHHELP .
YZTAB_TEMPLT_DET-DESCRIPTION =
YZ_V_TEMP_DET-DESCRIPTION .
YZTAB_TEMPLT_DET-FILTER_FIELD_NAME =
YZ_V_TEMP_DET-FILTER_FIELD_NAME .
YZTAB_TEMPLT_DET-AUTO_GENERATE =
YZ_V_TEMP_DET-AUTO_GENERATE .
YZTAB_TEMPLT_DET-SELECTION =
YZ_V_TEMP_DET-SELECTION .
YZTAB_TEMPLT_DET-IS_KEY =
YZ_V_TEMP_DET-IS_KEY .
YZTAB_TEMPLT_DET-INCLUDED =
YZ_V_TEMP_DET-INCLUDED .
YZTAB_TEMPLT_DET-USMD_ACTIVE =
YZ_V_TEMP_DET-USMD_ACTIVE .
    IF SY-SUBRC = 0.
    UPDATE YZTAB_TEMPLT_DET ##WARN_OK.
    ELSE.
    INSERT YZTAB_TEMPLT_DET .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_YZ_V_TEMP_DET-UPD_FLAG,
STATUS_YZ_V_TEMP_DET-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_YZ_V_TEMP_DET.
  SELECT SINGLE * FROM YZTAB_TEMPLT_DET WHERE
USMD_MODEL = YZ_V_TEMP_DET-USMD_MODEL AND
SCOPE_ID = YZ_V_TEMP_DET-SCOPE_ID AND
TEMPLATE_ID = YZ_V_TEMP_DET-TEMPLATE_ID AND
VIEW_ID = YZ_V_TEMP_DET-VIEW_ID AND
COLUMN_ID = YZ_V_TEMP_DET-COLUMN_ID AND
USMD_ENTITY = YZ_V_TEMP_DET-USMD_ENTITY .
YZ_V_TEMP_DET-CLIENT =
YZTAB_TEMPLT_DET-CLIENT .
YZ_V_TEMP_DET-USMD_MODEL =
YZTAB_TEMPLT_DET-USMD_MODEL .
YZ_V_TEMP_DET-SCOPE_ID =
YZTAB_TEMPLT_DET-SCOPE_ID .
YZ_V_TEMP_DET-TEMPLATE_ID =
YZTAB_TEMPLT_DET-TEMPLATE_ID .
YZ_V_TEMP_DET-VIEW_ID =
YZTAB_TEMPLT_DET-VIEW_ID .
YZ_V_TEMP_DET-COLUMN_ID =
YZTAB_TEMPLT_DET-COLUMN_ID .
YZ_V_TEMP_DET-USMD_ENTITY =
YZTAB_TEMPLT_DET-USMD_ENTITY .
YZ_V_TEMP_DET-USMD_ATTRIBUTE =
YZTAB_TEMPLT_DET-USMD_ATTRIBUTE .
YZ_V_TEMP_DET-ACTIVE_TAB_NAME =
YZTAB_TEMPLT_DET-ACTIVE_TAB_NAME .
YZ_V_TEMP_DET-ACTIVE_FIELD_NAME =
YZTAB_TEMPLT_DET-ACTIVE_FIELD_NAME .
YZ_V_TEMP_DET-FIELD_DOMAIN =
YZTAB_TEMPLT_DET-FIELD_DOMAIN .
YZ_V_TEMP_DET-SEARCHHELP =
YZTAB_TEMPLT_DET-SEARCHHELP .
YZ_V_TEMP_DET-DESCRIPTION =
YZTAB_TEMPLT_DET-DESCRIPTION .
YZ_V_TEMP_DET-FILTER_FIELD_NAME =
YZTAB_TEMPLT_DET-FILTER_FIELD_NAME .
YZ_V_TEMP_DET-AUTO_GENERATE =
YZTAB_TEMPLT_DET-AUTO_GENERATE .
YZ_V_TEMP_DET-SELECTION =
YZTAB_TEMPLT_DET-SELECTION .
YZ_V_TEMP_DET-IS_KEY =
YZTAB_TEMPLT_DET-IS_KEY .
YZ_V_TEMP_DET-INCLUDED =
YZTAB_TEMPLT_DET-INCLUDED .
YZ_V_TEMP_DET-USMD_ACTIVE =
YZTAB_TEMPLT_DET-USMD_ACTIVE .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_YZ_V_TEMP_DET USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE YZ_V_TEMP_DET-USMD_MODEL TO
YZTAB_TEMPLT_DET-USMD_MODEL .
MOVE YZ_V_TEMP_DET-SCOPE_ID TO
YZTAB_TEMPLT_DET-SCOPE_ID .
MOVE YZ_V_TEMP_DET-TEMPLATE_ID TO
YZTAB_TEMPLT_DET-TEMPLATE_ID .
MOVE YZ_V_TEMP_DET-VIEW_ID TO
YZTAB_TEMPLT_DET-VIEW_ID .
MOVE YZ_V_TEMP_DET-COLUMN_ID TO
YZTAB_TEMPLT_DET-COLUMN_ID .
MOVE YZ_V_TEMP_DET-USMD_ENTITY TO
YZTAB_TEMPLT_DET-USMD_ENTITY .
MOVE YZ_V_TEMP_DET-CLIENT TO
YZTAB_TEMPLT_DET-CLIENT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'YZTAB_TEMPLT_DET'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN YZTAB_TEMPLT_DET TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'YZTAB_TEMPLT_DET'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*

* base table related FORM-routines.............
INCLUDE LSVIMFTX .
