*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZMREF_MSTR_AGENT................................*
FORM GET_DATA_ZMREF_MSTR_AGENT.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZREF_MSTER_AGENT WHERE
(VIM_WHERETAB) .
    CLEAR ZMREF_MSTR_AGENT .
ZMREF_MSTR_AGENT-MANDT =
ZREF_MSTER_AGENT-MANDT .
ZMREF_MSTR_AGENT-OBJECT_CLASS =
ZREF_MSTER_AGENT-OBJECT_CLASS .
ZMREF_MSTR_AGENT-CHANGE_REQ_TYPE =
ZREF_MSTER_AGENT-CHANGE_REQ_TYPE .
ZMREF_MSTR_AGENT-APPROVER =
ZREF_MSTER_AGENT-APPROVER .
ZMREF_MSTR_AGENT-ACTIVE =
ZREF_MSTER_AGENT-ACTIVE .
<VIM_TOTAL_STRUC> = ZMREF_MSTR_AGENT.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZMREF_MSTR_AGENT .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZMREF_MSTR_AGENT.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZMREF_MSTR_AGENT-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZREF_MSTER_AGENT WHERE
  OBJECT_CLASS = ZMREF_MSTR_AGENT-OBJECT_CLASS AND
  CHANGE_REQ_TYPE = ZMREF_MSTR_AGENT-CHANGE_REQ_TYPE AND
  APPROVER = ZMREF_MSTR_AGENT-APPROVER .
    IF SY-SUBRC = 0.
    DELETE ZREF_MSTER_AGENT .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZREF_MSTER_AGENT WHERE
  OBJECT_CLASS = ZMREF_MSTR_AGENT-OBJECT_CLASS AND
  CHANGE_REQ_TYPE = ZMREF_MSTR_AGENT-CHANGE_REQ_TYPE AND
  APPROVER = ZMREF_MSTR_AGENT-APPROVER .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZREF_MSTER_AGENT.
    ENDIF.
ZREF_MSTER_AGENT-MANDT =
ZMREF_MSTR_AGENT-MANDT .
ZREF_MSTER_AGENT-OBJECT_CLASS =
ZMREF_MSTR_AGENT-OBJECT_CLASS .
ZREF_MSTER_AGENT-CHANGE_REQ_TYPE =
ZMREF_MSTR_AGENT-CHANGE_REQ_TYPE .
ZREF_MSTER_AGENT-APPROVER =
ZMREF_MSTR_AGENT-APPROVER .
ZREF_MSTER_AGENT-ACTIVE =
ZMREF_MSTR_AGENT-ACTIVE .
    IF SY-SUBRC = 0.
    UPDATE ZREF_MSTER_AGENT ##WARN_OK.
    ELSE.
    INSERT ZREF_MSTER_AGENT .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZMREF_MSTR_AGENT-UPD_FLAG,
STATUS_ZMREF_MSTR_AGENT-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZMREF_MSTR_AGENT.
  SELECT SINGLE * FROM ZREF_MSTER_AGENT WHERE
OBJECT_CLASS = ZMREF_MSTR_AGENT-OBJECT_CLASS AND
CHANGE_REQ_TYPE = ZMREF_MSTR_AGENT-CHANGE_REQ_TYPE AND
APPROVER = ZMREF_MSTR_AGENT-APPROVER .
ZMREF_MSTR_AGENT-MANDT =
ZREF_MSTER_AGENT-MANDT .
ZMREF_MSTR_AGENT-OBJECT_CLASS =
ZREF_MSTER_AGENT-OBJECT_CLASS .
ZMREF_MSTR_AGENT-CHANGE_REQ_TYPE =
ZREF_MSTER_AGENT-CHANGE_REQ_TYPE .
ZMREF_MSTR_AGENT-APPROVER =
ZREF_MSTER_AGENT-APPROVER .
ZMREF_MSTR_AGENT-ACTIVE =
ZREF_MSTER_AGENT-ACTIVE .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZMREF_MSTR_AGENT USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZMREF_MSTR_AGENT-OBJECT_CLASS TO
ZREF_MSTER_AGENT-OBJECT_CLASS .
MOVE ZMREF_MSTR_AGENT-CHANGE_REQ_TYPE TO
ZREF_MSTER_AGENT-CHANGE_REQ_TYPE .
MOVE ZMREF_MSTR_AGENT-APPROVER TO
ZREF_MSTER_AGENT-APPROVER .
MOVE ZMREF_MSTR_AGENT-MANDT TO
ZREF_MSTER_AGENT-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZREF_MSTER_AGENT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZREF_MSTER_AGENT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZREF_MSTER_AGENT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*

* base table related FORM-routines.............
INCLUDE LSVIMFTX .
