class YZ_CLAS_MDG_BP_DATA_PROCESS_EX definition
  public
  inheriting from YZ_CLAS_MDG_UTILITY
  create public .

public section.

  interfaces IF_MDG_BS_ECC_BP_DEFS .
  interfaces IF_MDG_BS_ECC_BP_CONSTANTS .
  interfaces IF_FSBP_CONST_PARTNER_TYPE .
  interfaces IF_FSBP_GENERIC_CONSTANTS .
  interfaces IF_MDG_BP_CONSTANTS .
  interfaces YZ_INTF_MDG_BP_DATA_TYPES_EX .
  interfaces YZ_INTF_MDG_BP_CONST .
  interfaces YZ_INTF_MDG_BP_DATA_TYPES .

  aliases ACTIVITY_CHANGE
    for IF_FSBP_GENERIC_CONSTANTS~ACTIVITY_CHANGE .
  aliases ACTIVITY_CREATE
    for IF_FSBP_GENERIC_CONSTANTS~ACTIVITY_CREATE .
  aliases ACTIVITY_DISPLAY
    for IF_FSBP_GENERIC_CONSTANTS~ACTIVITY_DISPLAY .
  aliases BP_HANDLE
    for IF_FSBP_GENERIC_CONSTANTS~BP_HANDLE .
  aliases COMP_DIFFERENT_LINES
    for IF_FSBP_GENERIC_CONSTANTS~COMP_DIFFERENT_LINES .
  aliases COMP_EXACT_LINES
    for IF_FSBP_GENERIC_CONSTANTS~COMP_EXACT_LINES .
  aliases COMP_SAME_KEY
    for IF_FSBP_GENERIC_CONSTANTS~COMP_SAME_KEY .
  aliases GC_ACTIVITY
    for IF_MDG_BP_CONSTANTS~GC_ACTIVITY .
  aliases GC_APP_SINGLE_MAINTENANCE
    for IF_MDG_BP_CONSTANTS~GC_APP_SINGLE_MAINTENANCE .
  aliases GC_AS_CAT_CUST
    for IF_MDG_BS_ECC_BP_DEFS~GC_AS_CAT_CUST .
  aliases GC_AS_CAT_SUPPL
    for IF_MDG_BS_ECC_BP_DEFS~GC_AS_CAT_SUPPL .
  aliases GC_BP_MODEL
    for IF_MDG_BP_CONSTANTS~GC_BP_MODEL .
  aliases GC_BP_MODEL_ENTITY
    for IF_MDG_BP_CONSTANTS~GC_BP_MODEL_ENTITY .
  aliases GC_BUSINESS_ACTIVITY
    for IF_MDG_BP_CONSTANTS~GC_BUSINESS_ACTIVITY .
  aliases GC_CLASS
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_CLASS .
  aliases GC_COUNTRY
    for IF_MDG_BP_CONSTANTS~GC_COUNTRY .
  aliases GC_CU_CLASS
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_CU_CLASS .
  aliases GC_CU_CLASSTYPE
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_CU_CLASSTYPE .
  aliases GC_CU_DOCUMENTS_UIBB
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_CU_DOCUMENTS_UIBB .
  aliases GC_CU_DOKOB
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_CU_DOKOB .
  aliases GC_CU_FIELD
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_CU_FIELD .
  aliases GC_CU_FIELD_EXT
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_CU_FIELD_EXT .
  aliases GC_CU_LOADING_FIELD
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_CU_LOADING_FIELD .
  aliases GC_CU_LONGTEXT_TYPE
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_CU_LONGTEXT_TYPE .
  aliases GC_CU_MLT_ASSIGNMENT_CAT
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_CU_MLT_ASSIGNMENT_CAT .
  aliases GC_CU_MODEL_ENTITY
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_CU_MODEL_ENTITY .
  aliases GC_CU_MODEL_TAG
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_CU_MODEL_TAG .
  aliases GC_CU_NO_RANGE_OBJECT
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_CU_NO_RANGE_OBJECT .
  aliases GC_CU_SALES_AREA
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_CU_SALES_AREA .
  aliases GC_CU_STD_MLT_ASSIGNMENT_ID
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_CU_STD_MLT_ASSIGNMENT_ID .
  aliases GC_DATE_MAX
    for IF_MDG_BP_CONSTANTS~GC_DATE_MAX .
  aliases GC_DATE_MIN
    for IF_MDG_BP_CONSTANTS~GC_DATE_MIN .
  aliases GC_ENRICHMENT_SPOT
    for IF_MDG_BP_CONSTANTS~GC_ENRICHMENT_SPOT .
  aliases GC_ERROR_HANDLER_LENGTH
    for IF_MDG_BP_CONSTANTS~GC_ERROR_HANDLER_LENGTH .
  aliases GC_ERROR_HANDLER_SIGN
    for IF_MDG_BP_CONSTANTS~GC_ERROR_HANDLER_SIGN .
  aliases GC_EVENT_BLOCK
    for IF_MDG_BP_CONSTANTS~GC_EVENT_BLOCK .
  aliases GC_EVENT_COPY
    for IF_MDG_BP_CONSTANTS~GC_EVENT_COPY .
  aliases GC_EVENT_CREATE
    for IF_MDG_BP_CONSTANTS~GC_EVENT_CREATE .
  aliases GC_EVENT_MARK_DELETION
    for IF_MDG_BP_CONSTANTS~GC_EVENT_MARK_DELETION .
  aliases GC_FIELD
    for IF_MDG_BP_CONSTANTS~GC_FIELD .
  aliases GC_INCOME_TAX_GERMANY
    for IF_MDG_BP_CONSTANTS~GC_INCOME_TAX_GERMANY .
  aliases GC_MAX_HITS
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_MAX_HITS .
  aliases GC_MA_AD_MODEL_ENTITY
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_MA_AD_MODEL_ENTITY .
  aliases GC_MA_FIELD
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_MA_FIELD .
  aliases GC_MA_INITIAL_ASSIGNMENT_ID
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_MA_INITIAL_ASSIGNMENT_ID .
  aliases GC_MA_MODEL_ENTITY
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_MA_MODEL_ENTITY .
  aliases GC_MORPH_SPOT_NAME
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_MORPH_SPOT_NAME .
  aliases GC_MSGID_UI
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_MSGID_UI .
  aliases GC_ORG_UNIT_MORPH_VALUE
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_ORG_UNIT_MORPH_VALUE .
  aliases GC_PARTNER_TYPE
    for IF_MDG_BP_CONSTANTS~GC_PARTNER_TYPE .
  aliases GC_PF_ALTERNATIVE_PAYEE
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_PF_ALTERNATIVE_PAYEE .
  aliases GC_PF_CONTACT_PERSON
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_PF_CONTACT_PERSON .
  aliases GC_PF_COUNTER_DEFAULT
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_PF_COUNTER_DEFAULT .
  aliases GC_PF_TYPE
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_PF_TYPE .
  aliases GC_PTAG_CREQ_MODE
    for IF_MDG_BP_CONSTANTS~GC_PTAG_CREQ_MODE .
  aliases GC_PTAG_EDITING_MODE
    for IF_MDG_BP_CONSTANTS~GC_PTAG_EDITING_MODE .
  aliases GC_PTAG_PROCESS
    for IF_MDG_BP_CONSTANTS~GC_PTAG_PROCESS .
  aliases GC_RELATION
    for IF_MDG_BP_CONSTANTS~GC_RELATION .
  aliases GC_SEARCH_HELP
    for IF_MDG_BP_CONSTANTS~GC_SEARCH_HELP .
  aliases GC_SEARCH_MODE
    for IF_MDG_BP_CONSTANTS~GC_SEARCH_MODE .
  aliases GC_SIMULATED_DB_RECORD
    for IF_MDG_BS_ECC_BP_DEFS~GC_SIMULATED_DB_RECORD .
  aliases GC_SP_CLASS
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_SP_CLASS .
  aliases GC_SP_CLASSTYPE
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_SP_CLASSTYPE .
  aliases GC_SP_DIF_PLANT_DEFAULT
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_SP_DIF_PLANT_DEFAULT .
  aliases GC_SP_DIF_SUBRANGE_DEFAULT
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_SP_DIF_SUBRANGE_DEFAULT .
  aliases GC_SP_DOCUMENTS_UIBB
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_SP_DOCUMENTS_UIBB .
  aliases GC_SP_DOKOB
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_SP_DOKOB .
  aliases GC_SP_FIELD
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_SP_FIELD .
  aliases GC_SP_FIELD_EXT
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_SP_FIELD_EXT .
  aliases GC_SP_LONGTEXT_TYPE
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_SP_LONGTEXT_TYPE .
  aliases GC_SP_MLT_ASSIGNMENT_CAT
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_SP_MLT_ASSIGNMENT_CAT .
  aliases GC_SP_MODEL_ENTITY
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_SP_MODEL_ENTITY .
  aliases GC_SP_MODEL_TAG
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_SP_MODEL_TAG .
  aliases GC_SP_NO_RANGE_OBJECT
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_SP_NO_RANGE_OBJECT .
  aliases GC_SP_STD_MLT_ASSIGNMENT_ID
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_SP_STD_MLT_ASSIGNMENT_ID .
  aliases GC_STANDARD_ADDRESS
    for IF_MDG_BP_CONSTANTS~GC_STANDARD_ADDRESS .
  aliases GC_STANDARD_AS_ID_CUST
    for IF_MDG_BS_ECC_BP_DEFS~GC_STANDARD_AS_ID_CUST .
  aliases GC_STANDARD_AS_ID_SUPPL
    for IF_MDG_BS_ECC_BP_DEFS~GC_STANDARD_AS_ID_SUPPL .
  aliases GC_TASK
    for IF_MDG_BP_CONSTANTS~GC_TASK .
  aliases GC_TIME_MIN
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_TIME_MIN .
  aliases GC_VENDOR_LIKE_UI
    for IF_MDG_BS_ECC_BP_CONSTANTS~GC_VENDOR_LIKE_UI .
  aliases GC_WORKPLACE_IAV_DUMMY
    for IF_MDG_BP_CONSTANTS~GC_WORKPLACE_IAV_DUMMY .
  aliases GROUP
    for IF_FSBP_CONST_PARTNER_TYPE~GROUP .
  aliases MSG_ABORT
    for IF_FSBP_GENERIC_CONSTANTS~MSG_ABORT .
  aliases MSG_ERROR
    for IF_FSBP_GENERIC_CONSTANTS~MSG_ERROR .
  aliases MSG_EXIT
    for IF_FSBP_GENERIC_CONSTANTS~MSG_EXIT .
  aliases MSG_INFO
    for IF_FSBP_GENERIC_CONSTANTS~MSG_INFO .
  aliases MSG_SUCCESS
    for IF_FSBP_GENERIC_CONSTANTS~MSG_SUCCESS .
  aliases MSG_WARNING
    for IF_FSBP_GENERIC_CONSTANTS~MSG_WARNING .
  aliases ORGANIZATION
    for IF_FSBP_CONST_PARTNER_TYPE~ORGANIZATION .
  aliases PERSON
    for IF_FSBP_CONST_PARTNER_TYPE~PERSON .

  types:
    tt_ZZENTITY_sample TYPE SORTED TABLE OF /mdg/_s_0g_pp_ACCCCDET WITH UNIQUE KEY coa account compcode .

  class-data GT_ZZENTITY_SAMPLE type TT_ZZENTITY_SAMPLE .
  constants GC_ZZENTITY_SAMPLE type USMD_ENTITY value 'ZZENTITY' ##NO_TEXT.

  methods CONSTRUCTOR .
  class-methods GET_ZZENTITY_SAMPLE
    exporting
      value(RT_DATA) type ref to DATA .
  class-methods SET_ZZENTITY_SAMPLE
    importing
      !IT_DATA type ANY TABLE .
  class-methods DEL_ZZENTITY_SAMPLE
    importing
      !IT_DATA type TT_ZZENTITY_SAMPLE .
protected section.
  PRIVATE SECTION.
ENDCLASS.



CLASS YZ_CLAS_MDG_BP_DATA_PROCESS_EX IMPLEMENTATION.


  METHOD CONSTRUCTOR.
    super->constructor( ).
  ENDMETHOD.


  METHOD DEL_ZZENTITY_SAMPLE.
    IF it_data IS NOT INITIAL.
      LOOP AT it_data INTO DATA(is_data) ##INTO_OK.
        DELETE TABLE gt_ZZENTITY_sample FROM is_data.
      ENDLOOP.
    ENDIF.
  ENDMETHOD.


  METHOD GET_ZZENTITY_SAMPLE.

    CREATE DATA rt_data TYPE tt_ZZENTITY_sample.

    ASSIGN rt_data->* TO FIELD-SYMBOL(<ft_data>).

    IF <ft_data> IS ASSIGNED.
      <ft_data> = gt_ZZENTITY_sample.
    ENDIF.
*fall back API
    CHECK rt_data IS INITIAL.
    CALL METHOD read_entity(
      EXPORTING
        iv_crequest = get_cr_number( )  " Change Request
        iv_entity   = gc_ZZENTITY_sample " Entity Type
        iv_readmode = gc_readmode_act_inact               " Read Mode
      IMPORTING
        eo_data_tab = rt_data ).


  ENDMETHOD.


  METHOD SET_ZZENTITY_SAMPLE.
    MOVE-CORRESPONDING it_data TO gt_ZZENTITY_sample.
  ENDMETHOD.
ENDCLASS.
