*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: YZ_VIEW_RULE_VAL................................*
FORM GET_DATA_YZ_VIEW_RULE_VAL.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM YZTABL_RULE_VAL WHERE
(VIM_WHERETAB) .
    CLEAR YZ_VIEW_RULE_VAL .
YZ_VIEW_RULE_VAL-MANDT =
YZTABL_RULE_VAL-MANDT .
YZ_VIEW_RULE_VAL-MODEL =
YZTABL_RULE_VAL-MODEL .
YZ_VIEW_RULE_VAL-OTC =
YZTABL_RULE_VAL-OTC .
YZ_VIEW_RULE_VAL-RULE_TYPE =
YZTABL_RULE_VAL-RULE_TYPE .
YZ_VIEW_RULE_VAL-DEF_ID =
YZTABL_RULE_VAL-DEF_ID .
YZ_VIEW_RULE_VAL-EXE_ID =
YZTABL_RULE_VAL-EXE_ID .
YZ_VIEW_RULE_VAL-RULE_SEC =
YZTABL_RULE_VAL-RULE_SEC .
YZ_VIEW_RULE_VAL-VAL_ID =
YZTABL_RULE_VAL-VAL_ID .
YZ_VIEW_RULE_VAL-SIGN =
YZTABL_RULE_VAL-SIGN .
YZ_VIEW_RULE_VAL-OPT =
YZTABL_RULE_VAL-OPT .
YZ_VIEW_RULE_VAL-VAL_TYPE =
YZTABL_RULE_VAL-VAL_TYPE .
YZ_VIEW_RULE_VAL-LOW =
YZTABL_RULE_VAL-LOW .
YZ_VIEW_RULE_VAL-HIGH =
YZTABL_RULE_VAL-HIGH .
YZ_VIEW_RULE_VAL-ACTIVE =
YZTABL_RULE_VAL-ACTIVE .
    SELECT SINGLE * FROM YZTABL_RULE_DEF WHERE
MODEL = YZTABL_RULE_VAL-MODEL AND
OTC = YZTABL_RULE_VAL-OTC AND
RULE_TYPE = YZTABL_RULE_VAL-RULE_TYPE AND
DEF_ID = YZTABL_RULE_VAL-DEF_ID .
    IF SY-SUBRC EQ 0.
YZ_VIEW_RULE_VAL-RULE_DEF =
YZTABL_RULE_DEF-RULE_DEF .
    ENDIF.
    SELECT SINGLE * FROM YZTABL_RULE_EXE WHERE
MODEL = YZTABL_RULE_VAL-MODEL AND
OTC = YZTABL_RULE_VAL-OTC AND
RULE_TYPE = YZTABL_RULE_VAL-RULE_TYPE AND
DEF_ID = YZTABL_RULE_VAL-DEF_ID AND
EXE_ID = YZTABL_RULE_VAL-EXE_ID AND
RULE_SEC = YZTABL_RULE_VAL-RULE_SEC .
    IF SY-SUBRC EQ 0.
YZ_VIEW_RULE_VAL-ENTITY =
YZTABL_RULE_EXE-ENTITY .
YZ_VIEW_RULE_VAL-ATTRIBUTE =
YZTABL_RULE_EXE-ATTRIBUTE .
      SELECT SINGLE * FROM YZTABL_RULE_SEC WHERE
RULE_SEC = YZTABL_RULE_EXE-RULE_SEC .
      IF SY-SUBRC EQ 0.
YZ_VIEW_RULE_VAL-SEC_DESC =
YZTABL_RULE_SEC-SEC_DESC .
      ENDIF.
    ENDIF.
    SELECT SINGLE * FROM YZTABL_RULE_TYP WHERE
RULE_TYPE = YZTABL_RULE_VAL-RULE_TYPE .
    IF SY-SUBRC EQ 0.
YZ_VIEW_RULE_VAL-TYPE_DESC =
YZTABL_RULE_TYP-TYPE_DESC .
    ENDIF.
<VIM_TOTAL_STRUC> = YZ_VIEW_RULE_VAL.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_YZ_VIEW_RULE_VAL .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO YZ_VIEW_RULE_VAL.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_YZ_VIEW_RULE_VAL-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM YZTABL_RULE_VAL WHERE
  MODEL = YZ_VIEW_RULE_VAL-MODEL AND
  OTC = YZ_VIEW_RULE_VAL-OTC AND
  RULE_TYPE = YZ_VIEW_RULE_VAL-RULE_TYPE AND
  DEF_ID = YZ_VIEW_RULE_VAL-DEF_ID AND
  EXE_ID = YZ_VIEW_RULE_VAL-EXE_ID AND
  RULE_SEC = YZ_VIEW_RULE_VAL-RULE_SEC AND
  VAL_ID = YZ_VIEW_RULE_VAL-VAL_ID .
    IF SY-SUBRC = 0.
    DELETE YZTABL_RULE_VAL .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM YZTABL_RULE_VAL WHERE
  MODEL = YZ_VIEW_RULE_VAL-MODEL AND
  OTC = YZ_VIEW_RULE_VAL-OTC AND
  RULE_TYPE = YZ_VIEW_RULE_VAL-RULE_TYPE AND
  DEF_ID = YZ_VIEW_RULE_VAL-DEF_ID AND
  EXE_ID = YZ_VIEW_RULE_VAL-EXE_ID AND
  RULE_SEC = YZ_VIEW_RULE_VAL-RULE_SEC AND
  VAL_ID = YZ_VIEW_RULE_VAL-VAL_ID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR YZTABL_RULE_VAL.
    ENDIF.
YZTABL_RULE_VAL-MANDT =
YZ_VIEW_RULE_VAL-MANDT .
YZTABL_RULE_VAL-MODEL =
YZ_VIEW_RULE_VAL-MODEL .
YZTABL_RULE_VAL-OTC =
YZ_VIEW_RULE_VAL-OTC .
YZTABL_RULE_VAL-RULE_TYPE =
YZ_VIEW_RULE_VAL-RULE_TYPE .
YZTABL_RULE_VAL-DEF_ID =
YZ_VIEW_RULE_VAL-DEF_ID .
YZTABL_RULE_VAL-EXE_ID =
YZ_VIEW_RULE_VAL-EXE_ID .
YZTABL_RULE_VAL-RULE_SEC =
YZ_VIEW_RULE_VAL-RULE_SEC .
YZTABL_RULE_VAL-VAL_ID =
YZ_VIEW_RULE_VAL-VAL_ID .
YZTABL_RULE_VAL-SIGN =
YZ_VIEW_RULE_VAL-SIGN .
YZTABL_RULE_VAL-OPT =
YZ_VIEW_RULE_VAL-OPT .
YZTABL_RULE_VAL-VAL_TYPE =
YZ_VIEW_RULE_VAL-VAL_TYPE .
YZTABL_RULE_VAL-LOW =
YZ_VIEW_RULE_VAL-LOW .
YZTABL_RULE_VAL-HIGH =
YZ_VIEW_RULE_VAL-HIGH .
YZTABL_RULE_VAL-ACTIVE =
YZ_VIEW_RULE_VAL-ACTIVE .
    IF SY-SUBRC = 0.
    UPDATE YZTABL_RULE_VAL ##WARN_OK.
    ELSE.
    INSERT YZTABL_RULE_VAL .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_YZ_VIEW_RULE_VAL-UPD_FLAG,
STATUS_YZ_VIEW_RULE_VAL-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_YZ_VIEW_RULE_VAL.
  SELECT SINGLE * FROM YZTABL_RULE_VAL WHERE
MODEL = YZ_VIEW_RULE_VAL-MODEL AND
OTC = YZ_VIEW_RULE_VAL-OTC AND
RULE_TYPE = YZ_VIEW_RULE_VAL-RULE_TYPE AND
DEF_ID = YZ_VIEW_RULE_VAL-DEF_ID AND
EXE_ID = YZ_VIEW_RULE_VAL-EXE_ID AND
RULE_SEC = YZ_VIEW_RULE_VAL-RULE_SEC AND
VAL_ID = YZ_VIEW_RULE_VAL-VAL_ID .
YZ_VIEW_RULE_VAL-MANDT =
YZTABL_RULE_VAL-MANDT .
YZ_VIEW_RULE_VAL-MODEL =
YZTABL_RULE_VAL-MODEL .
YZ_VIEW_RULE_VAL-OTC =
YZTABL_RULE_VAL-OTC .
YZ_VIEW_RULE_VAL-RULE_TYPE =
YZTABL_RULE_VAL-RULE_TYPE .
YZ_VIEW_RULE_VAL-DEF_ID =
YZTABL_RULE_VAL-DEF_ID .
YZ_VIEW_RULE_VAL-EXE_ID =
YZTABL_RULE_VAL-EXE_ID .
YZ_VIEW_RULE_VAL-RULE_SEC =
YZTABL_RULE_VAL-RULE_SEC .
YZ_VIEW_RULE_VAL-VAL_ID =
YZTABL_RULE_VAL-VAL_ID .
YZ_VIEW_RULE_VAL-SIGN =
YZTABL_RULE_VAL-SIGN .
YZ_VIEW_RULE_VAL-OPT =
YZTABL_RULE_VAL-OPT .
YZ_VIEW_RULE_VAL-VAL_TYPE =
YZTABL_RULE_VAL-VAL_TYPE .
YZ_VIEW_RULE_VAL-LOW =
YZTABL_RULE_VAL-LOW .
YZ_VIEW_RULE_VAL-HIGH =
YZTABL_RULE_VAL-HIGH .
YZ_VIEW_RULE_VAL-ACTIVE =
YZTABL_RULE_VAL-ACTIVE .
    SELECT SINGLE * FROM YZTABL_RULE_DEF WHERE
MODEL = YZTABL_RULE_VAL-MODEL AND
OTC = YZTABL_RULE_VAL-OTC AND
RULE_TYPE = YZTABL_RULE_VAL-RULE_TYPE AND
DEF_ID = YZTABL_RULE_VAL-DEF_ID .
    IF SY-SUBRC EQ 0.
YZ_VIEW_RULE_VAL-RULE_DEF =
YZTABL_RULE_DEF-RULE_DEF .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR YZ_VIEW_RULE_VAL-RULE_DEF .
    ENDIF.
    SELECT SINGLE * FROM YZTABL_RULE_EXE WHERE
MODEL = YZTABL_RULE_VAL-MODEL AND
OTC = YZTABL_RULE_VAL-OTC AND
RULE_TYPE = YZTABL_RULE_VAL-RULE_TYPE AND
DEF_ID = YZTABL_RULE_VAL-DEF_ID AND
EXE_ID = YZTABL_RULE_VAL-EXE_ID AND
RULE_SEC = YZTABL_RULE_VAL-RULE_SEC .
    IF SY-SUBRC EQ 0.
YZ_VIEW_RULE_VAL-ENTITY =
YZTABL_RULE_EXE-ENTITY .
YZ_VIEW_RULE_VAL-ATTRIBUTE =
YZTABL_RULE_EXE-ATTRIBUTE .
      SELECT SINGLE * FROM YZTABL_RULE_SEC WHERE
RULE_SEC = YZTABL_RULE_EXE-RULE_SEC .
      IF SY-SUBRC EQ 0.
YZ_VIEW_RULE_VAL-SEC_DESC =
YZTABL_RULE_SEC-SEC_DESC .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR YZ_VIEW_RULE_VAL-SEC_DESC .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR YZ_VIEW_RULE_VAL-ENTITY .
      CLEAR YZ_VIEW_RULE_VAL-ATTRIBUTE .
      CLEAR YZ_VIEW_RULE_VAL-SEC_DESC .
    ENDIF.
    SELECT SINGLE * FROM YZTABL_RULE_TYP WHERE
RULE_TYPE = YZTABL_RULE_VAL-RULE_TYPE .
    IF SY-SUBRC EQ 0.
YZ_VIEW_RULE_VAL-TYPE_DESC =
YZTABL_RULE_TYP-TYPE_DESC .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR YZ_VIEW_RULE_VAL-TYPE_DESC .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_YZ_VIEW_RULE_VAL USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE YZ_VIEW_RULE_VAL-MODEL TO
YZTABL_RULE_VAL-MODEL .
MOVE YZ_VIEW_RULE_VAL-OTC TO
YZTABL_RULE_VAL-OTC .
MOVE YZ_VIEW_RULE_VAL-RULE_TYPE TO
YZTABL_RULE_VAL-RULE_TYPE .
MOVE YZ_VIEW_RULE_VAL-DEF_ID TO
YZTABL_RULE_VAL-DEF_ID .
MOVE YZ_VIEW_RULE_VAL-EXE_ID TO
YZTABL_RULE_VAL-EXE_ID .
MOVE YZ_VIEW_RULE_VAL-RULE_SEC TO
YZTABL_RULE_VAL-RULE_SEC .
MOVE YZ_VIEW_RULE_VAL-VAL_ID TO
YZTABL_RULE_VAL-VAL_ID .
MOVE YZ_VIEW_RULE_VAL-MANDT TO
YZTABL_RULE_VAL-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'YZTABL_RULE_VAL'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN YZTABL_RULE_VAL TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'YZTABL_RULE_VAL'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_YZ_VIEW_RULE_VAL USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
YZTABL_RULE_VAL-MANDT =
YZ_VIEW_RULE_VAL-MANDT .
YZTABL_RULE_VAL-MODEL =
YZ_VIEW_RULE_VAL-MODEL .
YZTABL_RULE_VAL-OTC =
YZ_VIEW_RULE_VAL-OTC .
YZTABL_RULE_VAL-RULE_TYPE =
YZ_VIEW_RULE_VAL-RULE_TYPE .
YZTABL_RULE_VAL-DEF_ID =
YZ_VIEW_RULE_VAL-DEF_ID .
YZTABL_RULE_VAL-EXE_ID =
YZ_VIEW_RULE_VAL-EXE_ID .
YZTABL_RULE_VAL-RULE_SEC =
YZ_VIEW_RULE_VAL-RULE_SEC .
YZTABL_RULE_VAL-VAL_ID =
YZ_VIEW_RULE_VAL-VAL_ID .
YZTABL_RULE_VAL-SIGN =
YZ_VIEW_RULE_VAL-SIGN .
YZTABL_RULE_VAL-OPT =
YZ_VIEW_RULE_VAL-OPT .
YZTABL_RULE_VAL-VAL_TYPE =
YZ_VIEW_RULE_VAL-VAL_TYPE .
YZTABL_RULE_VAL-LOW =
YZ_VIEW_RULE_VAL-LOW .
YZTABL_RULE_VAL-HIGH =
YZ_VIEW_RULE_VAL-HIGH .
YZTABL_RULE_VAL-ACTIVE =
YZ_VIEW_RULE_VAL-ACTIVE .
    SELECT SINGLE * FROM YZTABL_RULE_DEF WHERE
MODEL = YZTABL_RULE_VAL-MODEL AND
OTC = YZTABL_RULE_VAL-OTC AND
RULE_TYPE = YZTABL_RULE_VAL-RULE_TYPE AND
DEF_ID = YZTABL_RULE_VAL-DEF_ID .
    IF SY-SUBRC EQ 0.
YZ_VIEW_RULE_VAL-RULE_DEF =
YZTABL_RULE_DEF-RULE_DEF .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR YZ_VIEW_RULE_VAL-RULE_DEF .
    ENDIF.
    SELECT SINGLE * FROM YZTABL_RULE_EXE WHERE
MODEL = YZTABL_RULE_VAL-MODEL AND
OTC = YZTABL_RULE_VAL-OTC AND
RULE_TYPE = YZTABL_RULE_VAL-RULE_TYPE AND
DEF_ID = YZTABL_RULE_VAL-DEF_ID AND
EXE_ID = YZTABL_RULE_VAL-EXE_ID AND
RULE_SEC = YZTABL_RULE_VAL-RULE_SEC .
    IF SY-SUBRC EQ 0.
YZ_VIEW_RULE_VAL-ENTITY =
YZTABL_RULE_EXE-ENTITY .
YZ_VIEW_RULE_VAL-ATTRIBUTE =
YZTABL_RULE_EXE-ATTRIBUTE .
      SELECT SINGLE * FROM YZTABL_RULE_SEC WHERE
RULE_SEC = YZTABL_RULE_EXE-RULE_SEC .
      IF SY-SUBRC EQ 0.
YZ_VIEW_RULE_VAL-SEC_DESC =
YZTABL_RULE_SEC-SEC_DESC .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR YZ_VIEW_RULE_VAL-SEC_DESC .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR YZ_VIEW_RULE_VAL-ENTITY .
      CLEAR YZ_VIEW_RULE_VAL-ATTRIBUTE .
      CLEAR YZ_VIEW_RULE_VAL-SEC_DESC .
    ENDIF.
    SELECT SINGLE * FROM YZTABL_RULE_TYP WHERE
RULE_TYPE = YZTABL_RULE_VAL-RULE_TYPE .
    IF SY-SUBRC EQ 0.
YZ_VIEW_RULE_VAL-TYPE_DESC =
YZTABL_RULE_TYP-TYPE_DESC .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR YZ_VIEW_RULE_VAL-TYPE_DESC .
    ENDIF.
ENDFORM.
