*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: YZ_VIEW_RULE_AUT................................*
FORM GET_DATA_YZ_VIEW_RULE_AUT.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM YZTABL_RULE_AUT WHERE
(VIM_WHERETAB) .
    CLEAR YZ_VIEW_RULE_AUT .
YZ_VIEW_RULE_AUT-MANDT =
YZTABL_RULE_AUT-MANDT .
YZ_VIEW_RULE_AUT-PHRASE =
YZTABL_RULE_AUT-PHRASE .
YZ_VIEW_RULE_AUT-FUZZY =
YZTABL_RULE_AUT-FUZZY .
YZ_VIEW_RULE_AUT-SEQNO =
YZTABL_RULE_AUT-SEQNO .
YZ_VIEW_RULE_AUT-ENTITY =
YZTABL_RULE_AUT-ENTITY .
YZ_VIEW_RULE_AUT-ATTRIBUTE =
YZTABL_RULE_AUT-ATTRIBUTE .
YZ_VIEW_RULE_AUT-VALUE_ID =
YZTABL_RULE_AUT-VALUE_ID .
YZ_VIEW_RULE_AUT-ACTIVE =
YZTABL_RULE_AUT-ACTIVE .
<VIM_TOTAL_STRUC> = YZ_VIEW_RULE_AUT.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_YZ_VIEW_RULE_AUT .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO YZ_VIEW_RULE_AUT.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_YZ_VIEW_RULE_AUT-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM YZTABL_RULE_AUT WHERE
  PHRASE = YZ_VIEW_RULE_AUT-PHRASE AND
  FUZZY = YZ_VIEW_RULE_AUT-FUZZY AND
  SEQNO = YZ_VIEW_RULE_AUT-SEQNO .
    IF SY-SUBRC = 0.
    DELETE YZTABL_RULE_AUT .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM YZTABL_RULE_AUT WHERE
  PHRASE = YZ_VIEW_RULE_AUT-PHRASE AND
  FUZZY = YZ_VIEW_RULE_AUT-FUZZY AND
  SEQNO = YZ_VIEW_RULE_AUT-SEQNO .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR YZTABL_RULE_AUT.
    ENDIF.
YZTABL_RULE_AUT-MANDT =
YZ_VIEW_RULE_AUT-MANDT .
YZTABL_RULE_AUT-PHRASE =
YZ_VIEW_RULE_AUT-PHRASE .
YZTABL_RULE_AUT-FUZZY =
YZ_VIEW_RULE_AUT-FUZZY .
YZTABL_RULE_AUT-SEQNO =
YZ_VIEW_RULE_AUT-SEQNO .
YZTABL_RULE_AUT-ENTITY =
YZ_VIEW_RULE_AUT-ENTITY .
YZTABL_RULE_AUT-ATTRIBUTE =
YZ_VIEW_RULE_AUT-ATTRIBUTE .
YZTABL_RULE_AUT-VALUE_ID =
YZ_VIEW_RULE_AUT-VALUE_ID .
YZTABL_RULE_AUT-ACTIVE =
YZ_VIEW_RULE_AUT-ACTIVE .
    IF SY-SUBRC = 0.
    UPDATE YZTABL_RULE_AUT ##WARN_OK.
    ELSE.
    INSERT YZTABL_RULE_AUT .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_YZ_VIEW_RULE_AUT-UPD_FLAG,
STATUS_YZ_VIEW_RULE_AUT-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_YZ_VIEW_RULE_AUT.
  SELECT SINGLE * FROM YZTABL_RULE_AUT WHERE
PHRASE = YZ_VIEW_RULE_AUT-PHRASE AND
FUZZY = YZ_VIEW_RULE_AUT-FUZZY AND
SEQNO = YZ_VIEW_RULE_AUT-SEQNO .
YZ_VIEW_RULE_AUT-MANDT =
YZTABL_RULE_AUT-MANDT .
YZ_VIEW_RULE_AUT-PHRASE =
YZTABL_RULE_AUT-PHRASE .
YZ_VIEW_RULE_AUT-FUZZY =
YZTABL_RULE_AUT-FUZZY .
YZ_VIEW_RULE_AUT-SEQNO =
YZTABL_RULE_AUT-SEQNO .
YZ_VIEW_RULE_AUT-ENTITY =
YZTABL_RULE_AUT-ENTITY .
YZ_VIEW_RULE_AUT-ATTRIBUTE =
YZTABL_RULE_AUT-ATTRIBUTE .
YZ_VIEW_RULE_AUT-VALUE_ID =
YZTABL_RULE_AUT-VALUE_ID .
YZ_VIEW_RULE_AUT-ACTIVE =
YZTABL_RULE_AUT-ACTIVE .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_YZ_VIEW_RULE_AUT USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE YZ_VIEW_RULE_AUT-PHRASE TO
YZTABL_RULE_AUT-PHRASE .
MOVE YZ_VIEW_RULE_AUT-FUZZY TO
YZTABL_RULE_AUT-FUZZY .
MOVE YZ_VIEW_RULE_AUT-SEQNO TO
YZTABL_RULE_AUT-SEQNO .
MOVE YZ_VIEW_RULE_AUT-MANDT TO
YZTABL_RULE_AUT-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'YZTABL_RULE_AUT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN YZTABL_RULE_AUT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'YZTABL_RULE_AUT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
