*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: YZ_VIEW_RULE_DOM................................*
FORM GET_DATA_YZ_VIEW_RULE_DOM.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM YZTABL_RULE_DOM WHERE
(VIM_WHERETAB) .
    CLEAR YZ_VIEW_RULE_DOM .
YZ_VIEW_RULE_DOM-MANDT =
YZTABL_RULE_DOM-MANDT .
YZ_VIEW_RULE_DOM-MODEL =
YZTABL_RULE_DOM-MODEL .
YZ_VIEW_RULE_DOM-OTC =
YZTABL_RULE_DOM-OTC .
YZ_VIEW_RULE_DOM-APP_LOG =
YZTABL_RULE_DOM-APP_LOG .
YZ_VIEW_RULE_DOM-BR_LOG =
YZTABL_RULE_DOM-BR_LOG .
YZ_VIEW_RULE_DOM-ACTIVE =
YZTABL_RULE_DOM-ACTIVE .
<VIM_TOTAL_STRUC> = YZ_VIEW_RULE_DOM.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_YZ_VIEW_RULE_DOM .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO YZ_VIEW_RULE_DOM.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_YZ_VIEW_RULE_DOM-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM YZTABL_RULE_DOM WHERE
  MODEL = YZ_VIEW_RULE_DOM-MODEL AND
  OTC = YZ_VIEW_RULE_DOM-OTC .
    IF SY-SUBRC = 0.
    DELETE YZTABL_RULE_DOM .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM YZTABL_RULE_DOM WHERE
  MODEL = YZ_VIEW_RULE_DOM-MODEL AND
  OTC = YZ_VIEW_RULE_DOM-OTC .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR YZTABL_RULE_DOM.
    ENDIF.
YZTABL_RULE_DOM-MANDT =
YZ_VIEW_RULE_DOM-MANDT .
YZTABL_RULE_DOM-MODEL =
YZ_VIEW_RULE_DOM-MODEL .
YZTABL_RULE_DOM-OTC =
YZ_VIEW_RULE_DOM-OTC .
YZTABL_RULE_DOM-APP_LOG =
YZ_VIEW_RULE_DOM-APP_LOG .
YZTABL_RULE_DOM-BR_LOG =
YZ_VIEW_RULE_DOM-BR_LOG .
YZTABL_RULE_DOM-ACTIVE =
YZ_VIEW_RULE_DOM-ACTIVE .
    IF SY-SUBRC = 0.
    UPDATE YZTABL_RULE_DOM ##WARN_OK.
    ELSE.
    INSERT YZTABL_RULE_DOM .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_YZ_VIEW_RULE_DOM-UPD_FLAG,
STATUS_YZ_VIEW_RULE_DOM-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_YZ_VIEW_RULE_DOM.
  SELECT SINGLE * FROM YZTABL_RULE_DOM WHERE
MODEL = YZ_VIEW_RULE_DOM-MODEL AND
OTC = YZ_VIEW_RULE_DOM-OTC .
YZ_VIEW_RULE_DOM-MANDT =
YZTABL_RULE_DOM-MANDT .
YZ_VIEW_RULE_DOM-MODEL =
YZTABL_RULE_DOM-MODEL .
YZ_VIEW_RULE_DOM-OTC =
YZTABL_RULE_DOM-OTC .
YZ_VIEW_RULE_DOM-APP_LOG =
YZTABL_RULE_DOM-APP_LOG .
YZ_VIEW_RULE_DOM-BR_LOG =
YZTABL_RULE_DOM-BR_LOG .
YZ_VIEW_RULE_DOM-ACTIVE =
YZTABL_RULE_DOM-ACTIVE .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_YZ_VIEW_RULE_DOM USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE YZ_VIEW_RULE_DOM-MODEL TO
YZTABL_RULE_DOM-MODEL .
MOVE YZ_VIEW_RULE_DOM-OTC TO
YZTABL_RULE_DOM-OTC .
MOVE YZ_VIEW_RULE_DOM-MANDT TO
YZTABL_RULE_DOM-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'YZTABL_RULE_DOM'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN YZTABL_RULE_DOM TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'YZTABL_RULE_DOM'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
