*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: YZ_VIEW_TEMP_ITM................................*
FORM GET_DATA_YZ_VIEW_TEMP_ITM.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM YZTABL_TEMP_ITM WHERE
(VIM_WHERETAB) .
    CLEAR YZ_VIEW_TEMP_ITM .
YZ_VIEW_TEMP_ITM-MANDT =
YZTABL_TEMP_ITM-MANDT .
YZ_VIEW_TEMP_ITM-MODEL =
YZTABL_TEMP_ITM-MODEL .
YZ_VIEW_TEMP_ITM-OTC =
YZTABL_TEMP_ITM-OTC .
YZ_VIEW_TEMP_ITM-RULE_TYPE =
YZTABL_TEMP_ITM-RULE_TYPE .
YZ_VIEW_TEMP_ITM-TEMP_ID =
YZTABL_TEMP_ITM-TEMP_ID .
YZ_VIEW_TEMP_ITM-EXE_ID =
YZTABL_TEMP_ITM-EXE_ID .
YZ_VIEW_TEMP_ITM-RULE_SEC =
YZTABL_TEMP_ITM-RULE_SEC .
YZ_VIEW_TEMP_ITM-SEQ_NO =
YZTABL_TEMP_ITM-SEQ_NO .
YZ_VIEW_TEMP_ITM-TASK =
YZTABL_TEMP_ITM-TASK .
YZ_VIEW_TEMP_ITM-OPERATION =
YZTABL_TEMP_ITM-OPERATION .
YZ_VIEW_TEMP_ITM-ENTITY =
YZTABL_TEMP_ITM-ENTITY .
YZ_VIEW_TEMP_ITM-ATTRIBUTE =
YZTABL_TEMP_ITM-ATTRIBUTE .
YZ_VIEW_TEMP_ITM-EXE_TYPE =
YZTABL_TEMP_ITM-EXE_TYPE .
YZ_VIEW_TEMP_ITM-VALUE_ID =
YZTABL_TEMP_ITM-VALUE_ID .
YZ_VIEW_TEMP_ITM-OPERATOR =
YZTABL_TEMP_ITM-OPERATOR .
YZ_VIEW_TEMP_ITM-CLASS =
YZTABL_TEMP_ITM-CLASS .
YZ_VIEW_TEMP_ITM-METHOD =
YZTABL_TEMP_ITM-METHOD .
YZ_VIEW_TEMP_ITM-ACTIVE =
YZTABL_TEMP_ITM-ACTIVE .
    SELECT SINGLE * FROM YZTABL_RULE_SEC WHERE
RULE_SEC = YZTABL_TEMP_ITM-RULE_SEC .
    IF SY-SUBRC EQ 0.
YZ_VIEW_TEMP_ITM-SEC_DESC =
YZTABL_RULE_SEC-SEC_DESC .
    ENDIF.
    SELECT * FROM YZTABL_RULE_TMP WHERE
TEMP_ID = YZTABL_TEMP_ITM-TEMP_ID .
YZ_VIEW_TEMP_ITM-TEMP_DESC =
YZTABL_RULE_TMP-TEMP_DESC .
      SELECT SINGLE * FROM YZTABL_RULE_TYP WHERE
RULE_TYPE = YZTABL_RULE_TMP-RULE_TYPE .
      IF SY-SUBRC EQ 0.
YZ_VIEW_TEMP_ITM-TYPE_DESC =
YZTABL_RULE_TYP-TYPE_DESC .
      ENDIF.
      EXIT.
    ENDSELECT.
<VIM_TOTAL_STRUC> = YZ_VIEW_TEMP_ITM.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_YZ_VIEW_TEMP_ITM .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO YZ_VIEW_TEMP_ITM.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_YZ_VIEW_TEMP_ITM-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM YZTABL_TEMP_ITM WHERE
  MODEL = YZ_VIEW_TEMP_ITM-MODEL AND
  OTC = YZ_VIEW_TEMP_ITM-OTC AND
  RULE_TYPE = YZ_VIEW_TEMP_ITM-RULE_TYPE AND
  TEMP_ID = YZ_VIEW_TEMP_ITM-TEMP_ID AND
  EXE_ID = YZ_VIEW_TEMP_ITM-EXE_ID AND
  RULE_SEC = YZ_VIEW_TEMP_ITM-RULE_SEC .
    IF SY-SUBRC = 0.
    DELETE YZTABL_TEMP_ITM .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM YZTABL_TEMP_ITM WHERE
  MODEL = YZ_VIEW_TEMP_ITM-MODEL AND
  OTC = YZ_VIEW_TEMP_ITM-OTC AND
  RULE_TYPE = YZ_VIEW_TEMP_ITM-RULE_TYPE AND
  TEMP_ID = YZ_VIEW_TEMP_ITM-TEMP_ID AND
  EXE_ID = YZ_VIEW_TEMP_ITM-EXE_ID AND
  RULE_SEC = YZ_VIEW_TEMP_ITM-RULE_SEC .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR YZTABL_TEMP_ITM.
    ENDIF.
YZTABL_TEMP_ITM-MANDT =
YZ_VIEW_TEMP_ITM-MANDT .
YZTABL_TEMP_ITM-MODEL =
YZ_VIEW_TEMP_ITM-MODEL .
YZTABL_TEMP_ITM-OTC =
YZ_VIEW_TEMP_ITM-OTC .
YZTABL_TEMP_ITM-RULE_TYPE =
YZ_VIEW_TEMP_ITM-RULE_TYPE .
YZTABL_TEMP_ITM-TEMP_ID =
YZ_VIEW_TEMP_ITM-TEMP_ID .
YZTABL_TEMP_ITM-EXE_ID =
YZ_VIEW_TEMP_ITM-EXE_ID .
YZTABL_TEMP_ITM-RULE_SEC =
YZ_VIEW_TEMP_ITM-RULE_SEC .
YZTABL_TEMP_ITM-SEQ_NO =
YZ_VIEW_TEMP_ITM-SEQ_NO .
YZTABL_TEMP_ITM-TASK =
YZ_VIEW_TEMP_ITM-TASK .
YZTABL_TEMP_ITM-OPERATION =
YZ_VIEW_TEMP_ITM-OPERATION .
YZTABL_TEMP_ITM-ENTITY =
YZ_VIEW_TEMP_ITM-ENTITY .
YZTABL_TEMP_ITM-ATTRIBUTE =
YZ_VIEW_TEMP_ITM-ATTRIBUTE .
YZTABL_TEMP_ITM-EXE_TYPE =
YZ_VIEW_TEMP_ITM-EXE_TYPE .
YZTABL_TEMP_ITM-VALUE_ID =
YZ_VIEW_TEMP_ITM-VALUE_ID .
YZTABL_TEMP_ITM-OPERATOR =
YZ_VIEW_TEMP_ITM-OPERATOR .
YZTABL_TEMP_ITM-CLASS =
YZ_VIEW_TEMP_ITM-CLASS .
YZTABL_TEMP_ITM-METHOD =
YZ_VIEW_TEMP_ITM-METHOD .
YZTABL_TEMP_ITM-ACTIVE =
YZ_VIEW_TEMP_ITM-ACTIVE .
    IF SY-SUBRC = 0.
    UPDATE YZTABL_TEMP_ITM ##WARN_OK.
    ELSE.
    INSERT YZTABL_TEMP_ITM .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_YZ_VIEW_TEMP_ITM-UPD_FLAG,
STATUS_YZ_VIEW_TEMP_ITM-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_YZ_VIEW_TEMP_ITM.
  SELECT SINGLE * FROM YZTABL_TEMP_ITM WHERE
MODEL = YZ_VIEW_TEMP_ITM-MODEL AND
OTC = YZ_VIEW_TEMP_ITM-OTC AND
RULE_TYPE = YZ_VIEW_TEMP_ITM-RULE_TYPE AND
TEMP_ID = YZ_VIEW_TEMP_ITM-TEMP_ID AND
EXE_ID = YZ_VIEW_TEMP_ITM-EXE_ID AND
RULE_SEC = YZ_VIEW_TEMP_ITM-RULE_SEC .
YZ_VIEW_TEMP_ITM-MANDT =
YZTABL_TEMP_ITM-MANDT .
YZ_VIEW_TEMP_ITM-MODEL =
YZTABL_TEMP_ITM-MODEL .
YZ_VIEW_TEMP_ITM-OTC =
YZTABL_TEMP_ITM-OTC .
YZ_VIEW_TEMP_ITM-RULE_TYPE =
YZTABL_TEMP_ITM-RULE_TYPE .
YZ_VIEW_TEMP_ITM-TEMP_ID =
YZTABL_TEMP_ITM-TEMP_ID .
YZ_VIEW_TEMP_ITM-EXE_ID =
YZTABL_TEMP_ITM-EXE_ID .
YZ_VIEW_TEMP_ITM-RULE_SEC =
YZTABL_TEMP_ITM-RULE_SEC .
YZ_VIEW_TEMP_ITM-SEQ_NO =
YZTABL_TEMP_ITM-SEQ_NO .
YZ_VIEW_TEMP_ITM-TASK =
YZTABL_TEMP_ITM-TASK .
YZ_VIEW_TEMP_ITM-OPERATION =
YZTABL_TEMP_ITM-OPERATION .
YZ_VIEW_TEMP_ITM-ENTITY =
YZTABL_TEMP_ITM-ENTITY .
YZ_VIEW_TEMP_ITM-ATTRIBUTE =
YZTABL_TEMP_ITM-ATTRIBUTE .
YZ_VIEW_TEMP_ITM-EXE_TYPE =
YZTABL_TEMP_ITM-EXE_TYPE .
YZ_VIEW_TEMP_ITM-VALUE_ID =
YZTABL_TEMP_ITM-VALUE_ID .
YZ_VIEW_TEMP_ITM-OPERATOR =
YZTABL_TEMP_ITM-OPERATOR .
YZ_VIEW_TEMP_ITM-CLASS =
YZTABL_TEMP_ITM-CLASS .
YZ_VIEW_TEMP_ITM-METHOD =
YZTABL_TEMP_ITM-METHOD .
YZ_VIEW_TEMP_ITM-ACTIVE =
YZTABL_TEMP_ITM-ACTIVE .
    SELECT SINGLE * FROM YZTABL_RULE_SEC WHERE
RULE_SEC = YZTABL_TEMP_ITM-RULE_SEC .
    IF SY-SUBRC EQ 0.
YZ_VIEW_TEMP_ITM-SEC_DESC =
YZTABL_RULE_SEC-SEC_DESC .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR YZ_VIEW_TEMP_ITM-SEC_DESC .
    ENDIF.
    SELECT * FROM YZTABL_RULE_TMP WHERE
TEMP_ID = YZTABL_TEMP_ITM-TEMP_ID .
YZ_VIEW_TEMP_ITM-TEMP_DESC =
YZTABL_RULE_TMP-TEMP_DESC .
      SELECT SINGLE * FROM YZTABL_RULE_TYP WHERE
RULE_TYPE = YZTABL_RULE_TMP-RULE_TYPE .
      IF SY-SUBRC EQ 0.
YZ_VIEW_TEMP_ITM-TYPE_DESC =
YZTABL_RULE_TYP-TYPE_DESC .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR YZ_VIEW_TEMP_ITM-TYPE_DESC .
      ENDIF.
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR YZ_VIEW_TEMP_ITM-TEMP_DESC .
      CLEAR YZ_VIEW_TEMP_ITM-TYPE_DESC .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_YZ_VIEW_TEMP_ITM USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE YZ_VIEW_TEMP_ITM-MODEL TO
YZTABL_TEMP_ITM-MODEL .
MOVE YZ_VIEW_TEMP_ITM-OTC TO
YZTABL_TEMP_ITM-OTC .
MOVE YZ_VIEW_TEMP_ITM-RULE_TYPE TO
YZTABL_TEMP_ITM-RULE_TYPE .
MOVE YZ_VIEW_TEMP_ITM-TEMP_ID TO
YZTABL_TEMP_ITM-TEMP_ID .
MOVE YZ_VIEW_TEMP_ITM-EXE_ID TO
YZTABL_TEMP_ITM-EXE_ID .
MOVE YZ_VIEW_TEMP_ITM-RULE_SEC TO
YZTABL_TEMP_ITM-RULE_SEC .
MOVE YZ_VIEW_TEMP_ITM-MANDT TO
YZTABL_TEMP_ITM-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'YZTABL_TEMP_ITM'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN YZTABL_TEMP_ITM TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'YZTABL_TEMP_ITM'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_YZ_VIEW_TEMP_ITM USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
YZTABL_TEMP_ITM-MANDT =
YZ_VIEW_TEMP_ITM-MANDT .
YZTABL_TEMP_ITM-MODEL =
YZ_VIEW_TEMP_ITM-MODEL .
YZTABL_TEMP_ITM-OTC =
YZ_VIEW_TEMP_ITM-OTC .
YZTABL_TEMP_ITM-RULE_TYPE =
YZ_VIEW_TEMP_ITM-RULE_TYPE .
YZTABL_TEMP_ITM-TEMP_ID =
YZ_VIEW_TEMP_ITM-TEMP_ID .
YZTABL_TEMP_ITM-EXE_ID =
YZ_VIEW_TEMP_ITM-EXE_ID .
YZTABL_TEMP_ITM-RULE_SEC =
YZ_VIEW_TEMP_ITM-RULE_SEC .
YZTABL_TEMP_ITM-SEQ_NO =
YZ_VIEW_TEMP_ITM-SEQ_NO .
YZTABL_TEMP_ITM-TASK =
YZ_VIEW_TEMP_ITM-TASK .
YZTABL_TEMP_ITM-OPERATION =
YZ_VIEW_TEMP_ITM-OPERATION .
YZTABL_TEMP_ITM-ENTITY =
YZ_VIEW_TEMP_ITM-ENTITY .
YZTABL_TEMP_ITM-ATTRIBUTE =
YZ_VIEW_TEMP_ITM-ATTRIBUTE .
YZTABL_TEMP_ITM-EXE_TYPE =
YZ_VIEW_TEMP_ITM-EXE_TYPE .
YZTABL_TEMP_ITM-VALUE_ID =
YZ_VIEW_TEMP_ITM-VALUE_ID .
YZTABL_TEMP_ITM-OPERATOR =
YZ_VIEW_TEMP_ITM-OPERATOR .
YZTABL_TEMP_ITM-CLASS =
YZ_VIEW_TEMP_ITM-CLASS .
YZTABL_TEMP_ITM-METHOD =
YZ_VIEW_TEMP_ITM-METHOD .
YZTABL_TEMP_ITM-ACTIVE =
YZ_VIEW_TEMP_ITM-ACTIVE .
    SELECT SINGLE * FROM YZTABL_RULE_SEC WHERE
RULE_SEC = YZTABL_TEMP_ITM-RULE_SEC .
    IF SY-SUBRC EQ 0.
YZ_VIEW_TEMP_ITM-SEC_DESC =
YZTABL_RULE_SEC-SEC_DESC .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR YZ_VIEW_TEMP_ITM-SEC_DESC .
    ENDIF.
    SELECT * FROM YZTABL_RULE_TMP WHERE
TEMP_ID = YZTABL_TEMP_ITM-TEMP_ID .
YZ_VIEW_TEMP_ITM-TEMP_DESC =
YZTABL_RULE_TMP-TEMP_DESC .
      SELECT SINGLE * FROM YZTABL_RULE_TYP WHERE
RULE_TYPE = YZTABL_RULE_TMP-RULE_TYPE .
      IF SY-SUBRC EQ 0.
YZ_VIEW_TEMP_ITM-TYPE_DESC =
YZTABL_RULE_TYP-TYPE_DESC .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR YZ_VIEW_TEMP_ITM-TYPE_DESC .
      ENDIF.
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR YZ_VIEW_TEMP_ITM-TEMP_DESC .
      CLEAR YZ_VIEW_TEMP_ITM-TYPE_DESC .
    ENDIF.
ENDFORM.
