*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: YZ_VIEW_CODE_DEB................................*
FORM GET_DATA_YZ_VIEW_CODE_DEB.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM YZTABL_CODE_DEB WHERE
(VIM_WHERETAB) .
    CLEAR YZ_VIEW_CODE_DEB .
YZ_VIEW_CODE_DEB-MANDT =
YZTABL_CODE_DEB-MANDT .
YZ_VIEW_CODE_DEB-PGMID =
YZTABL_CODE_DEB-PGMID .
YZ_VIEW_CODE_DEB-OBJTYPE =
YZTABL_CODE_DEB-OBJTYPE .
YZ_VIEW_CODE_DEB-OBJ_NAME =
YZTABL_CODE_DEB-OBJ_NAME .
YZ_VIEW_CODE_DEB-SOBJ_NAME =
YZTABL_CODE_DEB-SOBJ_NAME .
YZ_VIEW_CODE_DEB-UNAME =
YZTABL_CODE_DEB-UNAME .
YZ_VIEW_CODE_DEB-RESTRICT_DEBUG =
YZTABL_CODE_DEB-RESTRICT_DEBUG .
YZ_VIEW_CODE_DEB-ACTIVE =
YZTABL_CODE_DEB-ACTIVE .
<VIM_TOTAL_STRUC> = YZ_VIEW_CODE_DEB.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_YZ_VIEW_CODE_DEB .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO YZ_VIEW_CODE_DEB.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_YZ_VIEW_CODE_DEB-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM YZTABL_CODE_DEB WHERE
  PGMID = YZ_VIEW_CODE_DEB-PGMID AND
  OBJTYPE = YZ_VIEW_CODE_DEB-OBJTYPE AND
  OBJ_NAME = YZ_VIEW_CODE_DEB-OBJ_NAME AND
  SOBJ_NAME = YZ_VIEW_CODE_DEB-SOBJ_NAME AND
  UNAME = YZ_VIEW_CODE_DEB-UNAME .
    IF SY-SUBRC = 0.
    DELETE YZTABL_CODE_DEB .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM YZTABL_CODE_DEB WHERE
  PGMID = YZ_VIEW_CODE_DEB-PGMID AND
  OBJTYPE = YZ_VIEW_CODE_DEB-OBJTYPE AND
  OBJ_NAME = YZ_VIEW_CODE_DEB-OBJ_NAME AND
  SOBJ_NAME = YZ_VIEW_CODE_DEB-SOBJ_NAME AND
  UNAME = YZ_VIEW_CODE_DEB-UNAME .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR YZTABL_CODE_DEB.
    ENDIF.
YZTABL_CODE_DEB-MANDT =
YZ_VIEW_CODE_DEB-MANDT .
YZTABL_CODE_DEB-PGMID =
YZ_VIEW_CODE_DEB-PGMID .
YZTABL_CODE_DEB-OBJTYPE =
YZ_VIEW_CODE_DEB-OBJTYPE .
YZTABL_CODE_DEB-OBJ_NAME =
YZ_VIEW_CODE_DEB-OBJ_NAME .
YZTABL_CODE_DEB-SOBJ_NAME =
YZ_VIEW_CODE_DEB-SOBJ_NAME .
YZTABL_CODE_DEB-UNAME =
YZ_VIEW_CODE_DEB-UNAME .
YZTABL_CODE_DEB-RESTRICT_DEBUG =
YZ_VIEW_CODE_DEB-RESTRICT_DEBUG .
YZTABL_CODE_DEB-ACTIVE =
YZ_VIEW_CODE_DEB-ACTIVE .
    IF SY-SUBRC = 0.
    UPDATE YZTABL_CODE_DEB ##WARN_OK.
    ELSE.
    INSERT YZTABL_CODE_DEB .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_YZ_VIEW_CODE_DEB-UPD_FLAG,
STATUS_YZ_VIEW_CODE_DEB-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_YZ_VIEW_CODE_DEB.
  SELECT SINGLE * FROM YZTABL_CODE_DEB WHERE
PGMID = YZ_VIEW_CODE_DEB-PGMID AND
OBJTYPE = YZ_VIEW_CODE_DEB-OBJTYPE AND
OBJ_NAME = YZ_VIEW_CODE_DEB-OBJ_NAME AND
SOBJ_NAME = YZ_VIEW_CODE_DEB-SOBJ_NAME AND
UNAME = YZ_VIEW_CODE_DEB-UNAME .
YZ_VIEW_CODE_DEB-MANDT =
YZTABL_CODE_DEB-MANDT .
YZ_VIEW_CODE_DEB-PGMID =
YZTABL_CODE_DEB-PGMID .
YZ_VIEW_CODE_DEB-OBJTYPE =
YZTABL_CODE_DEB-OBJTYPE .
YZ_VIEW_CODE_DEB-OBJ_NAME =
YZTABL_CODE_DEB-OBJ_NAME .
YZ_VIEW_CODE_DEB-SOBJ_NAME =
YZTABL_CODE_DEB-SOBJ_NAME .
YZ_VIEW_CODE_DEB-UNAME =
YZTABL_CODE_DEB-UNAME .
YZ_VIEW_CODE_DEB-RESTRICT_DEBUG =
YZTABL_CODE_DEB-RESTRICT_DEBUG .
YZ_VIEW_CODE_DEB-ACTIVE =
YZTABL_CODE_DEB-ACTIVE .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_YZ_VIEW_CODE_DEB USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE YZ_VIEW_CODE_DEB-PGMID TO
YZTABL_CODE_DEB-PGMID .
MOVE YZ_VIEW_CODE_DEB-OBJTYPE TO
YZTABL_CODE_DEB-OBJTYPE .
MOVE YZ_VIEW_CODE_DEB-OBJ_NAME TO
YZTABL_CODE_DEB-OBJ_NAME .
MOVE YZ_VIEW_CODE_DEB-SOBJ_NAME TO
YZTABL_CODE_DEB-SOBJ_NAME .
MOVE YZ_VIEW_CODE_DEB-UNAME TO
YZTABL_CODE_DEB-UNAME .
MOVE YZ_VIEW_CODE_DEB-MANDT TO
YZTABL_CODE_DEB-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'YZTABL_CODE_DEB'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN YZTABL_CODE_DEB TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'YZTABL_CODE_DEB'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
