*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: YZ_VIEW_RULE_EXE................................*
FORM GET_DATA_YZ_VIEW_RULE_EXE.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM YZTABL_RULE_EXE WHERE
(VIM_WHERETAB) .
    CLEAR YZ_VIEW_RULE_EXE .
YZ_VIEW_RULE_EXE-MANDT =
YZTABL_RULE_EXE-MANDT .
YZ_VIEW_RULE_EXE-MODEL =
YZTABL_RULE_EXE-MODEL .
YZ_VIEW_RULE_EXE-OTC =
YZTABL_RULE_EXE-OTC .
YZ_VIEW_RULE_EXE-RULE_TYPE =
YZTABL_RULE_EXE-RULE_TYPE .
YZ_VIEW_RULE_EXE-DEF_ID =
YZTABL_RULE_EXE-DEF_ID .
YZ_VIEW_RULE_EXE-EXE_ID =
YZTABL_RULE_EXE-EXE_ID .
YZ_VIEW_RULE_EXE-RULE_SEC =
YZTABL_RULE_EXE-RULE_SEC .
YZ_VIEW_RULE_EXE-SEQ_NO =
YZTABL_RULE_EXE-SEQ_NO .
YZ_VIEW_RULE_EXE-TEMP_ID =
YZTABL_RULE_EXE-TEMP_ID .
YZ_VIEW_RULE_EXE-TASK =
YZTABL_RULE_EXE-TASK .
YZ_VIEW_RULE_EXE-OPERATION =
YZTABL_RULE_EXE-OPERATION .
YZ_VIEW_RULE_EXE-ENTITY =
YZTABL_RULE_EXE-ENTITY .
YZ_VIEW_RULE_EXE-ATTRIBUTE =
YZTABL_RULE_EXE-ATTRIBUTE .
YZ_VIEW_RULE_EXE-EXE_TYPE =
YZTABL_RULE_EXE-EXE_TYPE .
YZ_VIEW_RULE_EXE-VALUE_ID =
YZTABL_RULE_EXE-VALUE_ID .
YZ_VIEW_RULE_EXE-OPERATOR =
YZTABL_RULE_EXE-OPERATOR .
YZ_VIEW_RULE_EXE-CLASS =
YZTABL_RULE_EXE-CLASS .
YZ_VIEW_RULE_EXE-METHOD =
YZTABL_RULE_EXE-METHOD .
YZ_VIEW_RULE_EXE-ACTIVE =
YZTABL_RULE_EXE-ACTIVE .
YZ_VIEW_RULE_EXE-ORDER_ID =
YZTABL_RULE_EXE-ORDER_ID .
    SELECT SINGLE * FROM YZTABL_RULE_DEF WHERE
MODEL = YZTABL_RULE_EXE-MODEL AND
OTC = YZTABL_RULE_EXE-OTC AND
RULE_TYPE = YZTABL_RULE_EXE-RULE_TYPE AND
DEF_ID = YZTABL_RULE_EXE-DEF_ID .
    IF SY-SUBRC EQ 0.
YZ_VIEW_RULE_EXE-RULE_DEF =
YZTABL_RULE_DEF-RULE_DEF .
      SELECT SINGLE * FROM YZTABL_RULE_TYP WHERE
RULE_TYPE = YZTABL_RULE_DEF-RULE_TYPE .
      IF SY-SUBRC EQ 0.
YZ_VIEW_RULE_EXE-TYPE_DESC =
YZTABL_RULE_TYP-TYPE_DESC .
      ENDIF.
    ENDIF.
    SELECT SINGLE * FROM YZTABL_RULE_SEC WHERE
RULE_SEC = YZTABL_RULE_EXE-RULE_SEC .
    IF SY-SUBRC EQ 0.
    ENDIF.
<VIM_TOTAL_STRUC> = YZ_VIEW_RULE_EXE.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_YZ_VIEW_RULE_EXE .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO YZ_VIEW_RULE_EXE.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_YZ_VIEW_RULE_EXE-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM YZTABL_RULE_EXE WHERE
  MODEL = YZ_VIEW_RULE_EXE-MODEL AND
  OTC = YZ_VIEW_RULE_EXE-OTC AND
  RULE_TYPE = YZ_VIEW_RULE_EXE-RULE_TYPE AND
  DEF_ID = YZ_VIEW_RULE_EXE-DEF_ID AND
  EXE_ID = YZ_VIEW_RULE_EXE-EXE_ID AND
  RULE_SEC = YZ_VIEW_RULE_EXE-RULE_SEC .
    IF SY-SUBRC = 0.
    DELETE YZTABL_RULE_EXE .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM YZTABL_RULE_EXE WHERE
  MODEL = YZ_VIEW_RULE_EXE-MODEL AND
  OTC = YZ_VIEW_RULE_EXE-OTC AND
  RULE_TYPE = YZ_VIEW_RULE_EXE-RULE_TYPE AND
  DEF_ID = YZ_VIEW_RULE_EXE-DEF_ID AND
  EXE_ID = YZ_VIEW_RULE_EXE-EXE_ID AND
  RULE_SEC = YZ_VIEW_RULE_EXE-RULE_SEC .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR YZTABL_RULE_EXE.
    ENDIF.
YZTABL_RULE_EXE-MANDT =
YZ_VIEW_RULE_EXE-MANDT .
YZTABL_RULE_EXE-MODEL =
YZ_VIEW_RULE_EXE-MODEL .
YZTABL_RULE_EXE-OTC =
YZ_VIEW_RULE_EXE-OTC .
YZTABL_RULE_EXE-RULE_TYPE =
YZ_VIEW_RULE_EXE-RULE_TYPE .
YZTABL_RULE_EXE-DEF_ID =
YZ_VIEW_RULE_EXE-DEF_ID .
YZTABL_RULE_EXE-EXE_ID =
YZ_VIEW_RULE_EXE-EXE_ID .
YZTABL_RULE_EXE-RULE_SEC =
YZ_VIEW_RULE_EXE-RULE_SEC .
YZTABL_RULE_EXE-SEQ_NO =
YZ_VIEW_RULE_EXE-SEQ_NO .
YZTABL_RULE_EXE-TEMP_ID =
YZ_VIEW_RULE_EXE-TEMP_ID .
YZTABL_RULE_EXE-TASK =
YZ_VIEW_RULE_EXE-TASK .
YZTABL_RULE_EXE-OPERATION =
YZ_VIEW_RULE_EXE-OPERATION .
YZTABL_RULE_EXE-ENTITY =
YZ_VIEW_RULE_EXE-ENTITY .
YZTABL_RULE_EXE-ATTRIBUTE =
YZ_VIEW_RULE_EXE-ATTRIBUTE .
YZTABL_RULE_EXE-EXE_TYPE =
YZ_VIEW_RULE_EXE-EXE_TYPE .
YZTABL_RULE_EXE-VALUE_ID =
YZ_VIEW_RULE_EXE-VALUE_ID .
YZTABL_RULE_EXE-OPERATOR =
YZ_VIEW_RULE_EXE-OPERATOR .
YZTABL_RULE_EXE-CLASS =
YZ_VIEW_RULE_EXE-CLASS .
YZTABL_RULE_EXE-METHOD =
YZ_VIEW_RULE_EXE-METHOD .
YZTABL_RULE_EXE-ACTIVE =
YZ_VIEW_RULE_EXE-ACTIVE .
YZTABL_RULE_EXE-ORDER_ID =
YZ_VIEW_RULE_EXE-ORDER_ID .
    IF SY-SUBRC = 0.
    UPDATE YZTABL_RULE_EXE ##WARN_OK.
    ELSE.
    INSERT YZTABL_RULE_EXE .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_YZ_VIEW_RULE_EXE-UPD_FLAG,
STATUS_YZ_VIEW_RULE_EXE-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_YZ_VIEW_RULE_EXE.
  SELECT SINGLE * FROM YZTABL_RULE_EXE WHERE
MODEL = YZ_VIEW_RULE_EXE-MODEL AND
OTC = YZ_VIEW_RULE_EXE-OTC AND
RULE_TYPE = YZ_VIEW_RULE_EXE-RULE_TYPE AND
DEF_ID = YZ_VIEW_RULE_EXE-DEF_ID AND
EXE_ID = YZ_VIEW_RULE_EXE-EXE_ID AND
RULE_SEC = YZ_VIEW_RULE_EXE-RULE_SEC .
YZ_VIEW_RULE_EXE-MANDT =
YZTABL_RULE_EXE-MANDT .
YZ_VIEW_RULE_EXE-MODEL =
YZTABL_RULE_EXE-MODEL .
YZ_VIEW_RULE_EXE-OTC =
YZTABL_RULE_EXE-OTC .
YZ_VIEW_RULE_EXE-RULE_TYPE =
YZTABL_RULE_EXE-RULE_TYPE .
YZ_VIEW_RULE_EXE-DEF_ID =
YZTABL_RULE_EXE-DEF_ID .
YZ_VIEW_RULE_EXE-EXE_ID =
YZTABL_RULE_EXE-EXE_ID .
YZ_VIEW_RULE_EXE-RULE_SEC =
YZTABL_RULE_EXE-RULE_SEC .
YZ_VIEW_RULE_EXE-SEQ_NO =
YZTABL_RULE_EXE-SEQ_NO .
YZ_VIEW_RULE_EXE-TEMP_ID =
YZTABL_RULE_EXE-TEMP_ID .
YZ_VIEW_RULE_EXE-TASK =
YZTABL_RULE_EXE-TASK .
YZ_VIEW_RULE_EXE-OPERATION =
YZTABL_RULE_EXE-OPERATION .
YZ_VIEW_RULE_EXE-ENTITY =
YZTABL_RULE_EXE-ENTITY .
YZ_VIEW_RULE_EXE-ATTRIBUTE =
YZTABL_RULE_EXE-ATTRIBUTE .
YZ_VIEW_RULE_EXE-EXE_TYPE =
YZTABL_RULE_EXE-EXE_TYPE .
YZ_VIEW_RULE_EXE-VALUE_ID =
YZTABL_RULE_EXE-VALUE_ID .
YZ_VIEW_RULE_EXE-OPERATOR =
YZTABL_RULE_EXE-OPERATOR .
YZ_VIEW_RULE_EXE-CLASS =
YZTABL_RULE_EXE-CLASS .
YZ_VIEW_RULE_EXE-METHOD =
YZTABL_RULE_EXE-METHOD .
YZ_VIEW_RULE_EXE-ACTIVE =
YZTABL_RULE_EXE-ACTIVE .
YZ_VIEW_RULE_EXE-ORDER_ID =
YZTABL_RULE_EXE-ORDER_ID .
    SELECT SINGLE * FROM YZTABL_RULE_DEF WHERE
MODEL = YZTABL_RULE_EXE-MODEL AND
OTC = YZTABL_RULE_EXE-OTC AND
RULE_TYPE = YZTABL_RULE_EXE-RULE_TYPE AND
DEF_ID = YZTABL_RULE_EXE-DEF_ID .
    IF SY-SUBRC EQ 0.
YZ_VIEW_RULE_EXE-RULE_DEF =
YZTABL_RULE_DEF-RULE_DEF .
      SELECT SINGLE * FROM YZTABL_RULE_TYP WHERE
RULE_TYPE = YZTABL_RULE_DEF-RULE_TYPE .
      IF SY-SUBRC EQ 0.
YZ_VIEW_RULE_EXE-TYPE_DESC =
YZTABL_RULE_TYP-TYPE_DESC .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR YZ_VIEW_RULE_EXE-TYPE_DESC .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR YZ_VIEW_RULE_EXE-RULE_DEF .
      CLEAR YZ_VIEW_RULE_EXE-TYPE_DESC .
    ENDIF.
    SELECT SINGLE * FROM YZTABL_RULE_SEC WHERE
RULE_SEC = YZTABL_RULE_EXE-RULE_SEC .
    IF SY-SUBRC EQ 0.
    ELSE.
      CLEAR SY-SUBRC.
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_YZ_VIEW_RULE_EXE USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE YZ_VIEW_RULE_EXE-MODEL TO
YZTABL_RULE_EXE-MODEL .
MOVE YZ_VIEW_RULE_EXE-OTC TO
YZTABL_RULE_EXE-OTC .
MOVE YZ_VIEW_RULE_EXE-RULE_TYPE TO
YZTABL_RULE_EXE-RULE_TYPE .
MOVE YZ_VIEW_RULE_EXE-DEF_ID TO
YZTABL_RULE_EXE-DEF_ID .
MOVE YZ_VIEW_RULE_EXE-EXE_ID TO
YZTABL_RULE_EXE-EXE_ID .
MOVE YZ_VIEW_RULE_EXE-RULE_SEC TO
YZTABL_RULE_EXE-RULE_SEC .
MOVE YZ_VIEW_RULE_EXE-MANDT TO
YZTABL_RULE_EXE-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'YZTABL_RULE_EXE'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN YZTABL_RULE_EXE TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'YZTABL_RULE_EXE'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_YZ_VIEW_RULE_EXE USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
YZTABL_RULE_EXE-MANDT =
YZ_VIEW_RULE_EXE-MANDT .
YZTABL_RULE_EXE-MODEL =
YZ_VIEW_RULE_EXE-MODEL .
YZTABL_RULE_EXE-OTC =
YZ_VIEW_RULE_EXE-OTC .
YZTABL_RULE_EXE-RULE_TYPE =
YZ_VIEW_RULE_EXE-RULE_TYPE .
YZTABL_RULE_EXE-DEF_ID =
YZ_VIEW_RULE_EXE-DEF_ID .
YZTABL_RULE_EXE-EXE_ID =
YZ_VIEW_RULE_EXE-EXE_ID .
YZTABL_RULE_EXE-RULE_SEC =
YZ_VIEW_RULE_EXE-RULE_SEC .
YZTABL_RULE_EXE-SEQ_NO =
YZ_VIEW_RULE_EXE-SEQ_NO .
YZTABL_RULE_EXE-TEMP_ID =
YZ_VIEW_RULE_EXE-TEMP_ID .
YZTABL_RULE_EXE-TASK =
YZ_VIEW_RULE_EXE-TASK .
YZTABL_RULE_EXE-OPERATION =
YZ_VIEW_RULE_EXE-OPERATION .
YZTABL_RULE_EXE-ENTITY =
YZ_VIEW_RULE_EXE-ENTITY .
YZTABL_RULE_EXE-ATTRIBUTE =
YZ_VIEW_RULE_EXE-ATTRIBUTE .
YZTABL_RULE_EXE-EXE_TYPE =
YZ_VIEW_RULE_EXE-EXE_TYPE .
YZTABL_RULE_EXE-VALUE_ID =
YZ_VIEW_RULE_EXE-VALUE_ID .
YZTABL_RULE_EXE-OPERATOR =
YZ_VIEW_RULE_EXE-OPERATOR .
YZTABL_RULE_EXE-CLASS =
YZ_VIEW_RULE_EXE-CLASS .
YZTABL_RULE_EXE-METHOD =
YZ_VIEW_RULE_EXE-METHOD .
YZTABL_RULE_EXE-ACTIVE =
YZ_VIEW_RULE_EXE-ACTIVE .
YZTABL_RULE_EXE-ORDER_ID =
YZ_VIEW_RULE_EXE-ORDER_ID .
    SELECT SINGLE * FROM YZTABL_RULE_DEF WHERE
MODEL = YZTABL_RULE_EXE-MODEL AND
OTC = YZTABL_RULE_EXE-OTC AND
RULE_TYPE = YZTABL_RULE_EXE-RULE_TYPE AND
DEF_ID = YZTABL_RULE_EXE-DEF_ID .
    IF SY-SUBRC EQ 0.
YZ_VIEW_RULE_EXE-RULE_DEF =
YZTABL_RULE_DEF-RULE_DEF .
      SELECT SINGLE * FROM YZTABL_RULE_TYP WHERE
RULE_TYPE = YZTABL_RULE_DEF-RULE_TYPE .
      IF SY-SUBRC EQ 0.
YZ_VIEW_RULE_EXE-TYPE_DESC =
YZTABL_RULE_TYP-TYPE_DESC .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR YZ_VIEW_RULE_EXE-TYPE_DESC .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR YZ_VIEW_RULE_EXE-RULE_DEF .
      CLEAR YZ_VIEW_RULE_EXE-TYPE_DESC .
    ENDIF.
    SELECT SINGLE * FROM YZTABL_RULE_SEC WHERE
RULE_SEC = YZTABL_RULE_EXE-RULE_SEC .
    IF SY-SUBRC EQ 0.
    ELSE.
      CLEAR SY-SUBRC.
    ENDIF.
ENDFORM.
